# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetProfileResult',
    'AwaitableGetProfileResult',
    'get_profile',
    'get_profile_output',
]

@pulumi.output_type
class GetProfileResult:
    """
    A collection of values returned by getProfile.
    """
    def __init__(__self__, connection_id=None, credentials_id=None, extended_attributes_id=None, id=None, key=None, profile_id=None, project_id=None):
        if connection_id and not isinstance(connection_id, int):
            raise TypeError("Expected argument 'connection_id' to be a int")
        pulumi.set(__self__, "connection_id", connection_id)
        if credentials_id and not isinstance(credentials_id, int):
            raise TypeError("Expected argument 'credentials_id' to be a int")
        pulumi.set(__self__, "credentials_id", credentials_id)
        if extended_attributes_id and not isinstance(extended_attributes_id, int):
            raise TypeError("Expected argument 'extended_attributes_id' to be a int")
        pulumi.set(__self__, "extended_attributes_id", extended_attributes_id)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if key and not isinstance(key, str):
            raise TypeError("Expected argument 'key' to be a str")
        pulumi.set(__self__, "key", key)
        if profile_id and not isinstance(profile_id, int):
            raise TypeError("Expected argument 'profile_id' to be a int")
        pulumi.set(__self__, "profile_id", profile_id)
        if project_id and not isinstance(project_id, int):
            raise TypeError("Expected argument 'project_id' to be a int")
        pulumi.set(__self__, "project_id", project_id)

    @_builtins.property
    @pulumi.getter(name="connectionId")
    def connection_id(self) -> _builtins.int:
        """
        The ID of the connection used by this profile
        """
        return pulumi.get(self, "connection_id")

    @_builtins.property
    @pulumi.getter(name="credentialsId")
    def credentials_id(self) -> _builtins.int:
        """
        The ID of the credentials used by this profile
        """
        return pulumi.get(self, "credentials_id")

    @_builtins.property
    @pulumi.getter(name="extendedAttributesId")
    def extended_attributes_id(self) -> _builtins.int:
        """
        The ID of the extended attributes for this profile
        """
        return pulumi.get(self, "extended_attributes_id")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The ID of this resource. Contains the project ID and the profile ID.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def key(self) -> _builtins.str:
        """
        Unique identifier for the profile
        """
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter(name="profileId")
    def profile_id(self) -> _builtins.int:
        """
        The ID of the profile
        """
        return pulumi.get(self, "profile_id")

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> _builtins.int:
        """
        The project ID to which the profile belongs
        """
        return pulumi.get(self, "project_id")


class AwaitableGetProfileResult(GetProfileResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetProfileResult(
            connection_id=self.connection_id,
            credentials_id=self.credentials_id,
            extended_attributes_id=self.extended_attributes_id,
            id=self.id,
            key=self.key,
            profile_id=self.profile_id,
            project_id=self.project_id)


def get_profile(profile_id: Optional[_builtins.int] = None,
                project_id: Optional[_builtins.int] = None,
                opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetProfileResult:
    """
    Retrieve data for a single profile

    ## Example Usage

    ```python
    import pulumi
    import pulumi_dbtcloud as dbtcloud

    my_profile = dbtcloud.get_profile(profile_id=12345,
        project_id=6789)
    ```


    :param _builtins.int profile_id: The ID of the profile
    :param _builtins.int project_id: The project ID to which the profile belongs
    """
    __args__ = dict()
    __args__['profileId'] = profile_id
    __args__['projectId'] = project_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('dbtcloud:index/getProfile:getProfile', __args__, opts=opts, typ=GetProfileResult).value

    return AwaitableGetProfileResult(
        connection_id=pulumi.get(__ret__, 'connection_id'),
        credentials_id=pulumi.get(__ret__, 'credentials_id'),
        extended_attributes_id=pulumi.get(__ret__, 'extended_attributes_id'),
        id=pulumi.get(__ret__, 'id'),
        key=pulumi.get(__ret__, 'key'),
        profile_id=pulumi.get(__ret__, 'profile_id'),
        project_id=pulumi.get(__ret__, 'project_id'))
def get_profile_output(profile_id: Optional[pulumi.Input[_builtins.int]] = None,
                       project_id: Optional[pulumi.Input[_builtins.int]] = None,
                       opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetProfileResult]:
    """
    Retrieve data for a single profile

    ## Example Usage

    ```python
    import pulumi
    import pulumi_dbtcloud as dbtcloud

    my_profile = dbtcloud.get_profile(profile_id=12345,
        project_id=6789)
    ```


    :param _builtins.int profile_id: The ID of the profile
    :param _builtins.int project_id: The project ID to which the profile belongs
    """
    __args__ = dict()
    __args__['profileId'] = profile_id
    __args__['projectId'] = project_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('dbtcloud:index/getProfile:getProfile', __args__, opts=opts, typ=GetProfileResult)
    return __ret__.apply(lambda __response__: GetProfileResult(
        connection_id=pulumi.get(__response__, 'connection_id'),
        credentials_id=pulumi.get(__response__, 'credentials_id'),
        extended_attributes_id=pulumi.get(__response__, 'extended_attributes_id'),
        id=pulumi.get(__response__, 'id'),
        key=pulumi.get(__response__, 'key'),
        profile_id=pulumi.get(__response__, 'profile_id'),
        project_id=pulumi.get(__response__, 'project_id')))
