// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dbtcloud;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.dbtcloud.AuthProviderArgs;
import com.pulumi.dbtcloud.Utilities;
import com.pulumi.dbtcloud.inputs.AuthProviderState;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * Manages an SSO auth provider for a dbt Cloud account. Supports SAML/Okta, Azure Active Directory (single-tenant, multi-tenant), and Google Workspace.
 * 
 * Only one auth provider may exist per account. Requires the SSO feature enabled on the account (enterprise plans only).
 * 
 * See the [documentation](https://docs.getdbt.com/docs/cloud/manage-access/sso-overview) for more information.
 * 
 * ## Import
 * 
 * Import an existing auth provider by its numeric ID.
 * The ID can be found via the dbt Cloud API:
 * GET /api/v3/accounts/{account_id}/auth-provider/
 * 
 * ```sh
 * $ pulumi import dbtcloud:index/authProvider:AuthProvider example 12345
 * ```
 * 
 */
@ResourceType(type="dbtcloud:index/authProvider:AuthProvider")
public class AuthProvider extends com.pulumi.resources.CustomResource {
    /**
     * Google Workspace admin OAuth refresh token used to fetch group memberships.
     * 
     */
    @Export(name="adminRefreshToken", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> adminRefreshToken;

    /**
     * @return Google Workspace admin OAuth refresh token used to fetch group memberships.
     * 
     */
    public Output<Optional<String>> adminRefreshToken() {
        return Codegen.optional(this.adminRefreshToken);
    }
    /**
     * When true (default), users can still log in with email and password as a fallback. Set to false to enforce SSO-only access.
     * 
     */
    @Export(name="allowPasswordBackdoor", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> allowPasswordBackdoor;

    /**
     * @return When true (default), users can still log in with email and password as a fallback. Set to false to enforce SSO-only access.
     * 
     */
    public Output<Boolean> allowPasswordBackdoor() {
        return this.allowPasswordBackdoor;
    }
    /**
     * JSON map of SAML attribute names to dbt Cloud user fields.
     * 
     */
    @Export(name="attributeMap", refs={String.class}, tree="[0]")
    private Output<String> attributeMap;

    /**
     * @return JSON map of SAML attribute names to dbt Cloud user fields.
     * 
     */
    public Output<String> attributeMap() {
        return this.attributeMap;
    }
    /**
     * OAuth authorization URL for Google Workspace. May be auto-populated server-side.
     * 
     */
    @Export(name="authorizationUrl", refs={String.class}, tree="[0]")
    private Output<String> authorizationUrl;

    /**
     * @return OAuth authorization URL for Google Workspace. May be auto-populated server-side.
     * 
     */
    public Output<String> authorizationUrl() {
        return this.authorizationUrl;
    }
    /**
     * SAML X.509 certificate (PEM format). Sensitive — stored in state. Consider using `certWo` instead. Conflicts with `certWo`.
     * 
     */
    @Export(name="cert", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> cert;

    /**
     * @return SAML X.509 certificate (PEM format). Sensitive — stored in state. Consider using `certWo` instead. Conflicts with `certWo`.
     * 
     */
    public Output<Optional<String>> cert() {
        return Codegen.optional(this.cert);
    }
    /**
     * Expiry date of the SAML X.509 certificate (SAML/Okta only).
     * 
     */
    @Export(name="certExpiryDate", refs={String.class}, tree="[0]")
    private Output<String> certExpiryDate;

    /**
     * @return Expiry date of the SAML X.509 certificate (SAML/Okta only).
     * 
     */
    public Output<String> certExpiryDate() {
        return this.certExpiryDate;
    }
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Write-only alternative to `cert`. Not stored in state. Use `certWoVersion` to trigger updates. Conflicts with `cert`.
     * 
     */
    @Export(name="certWo", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> certWo;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Write-only alternative to `cert`. Not stored in state. Use `certWoVersion` to trigger updates. Conflicts with `cert`.
     * 
     */
    public Output<Optional<String>> certWo() {
        return Codegen.optional(this.certWo);
    }
    /**
     * Increment to rotate `certWo` without changing the value.
     * 
     */
    @Export(name="certWoVersion", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> certWoVersion;

    /**
     * @return Increment to rotate `certWo` without changing the value.
     * 
     */
    public Output<Optional<Integer>> certWoVersion() {
        return Codegen.optional(this.certWoVersion);
    }
    /**
     * OAuth client ID. Required for Azure AD and Google Workspace providers. Not returned by the API after save (encrypted at rest).
     * 
     */
    @Export(name="clientId", refs={String.class}, tree="[0]")
    private Output<String> clientId;

    /**
     * @return OAuth client ID. Required for Azure AD and Google Workspace providers. Not returned by the API after save (encrypted at rest).
     * 
     */
    public Output<String> clientId() {
        return this.clientId;
    }
    /**
     * OAuth client secret. Required for Azure AD and Google Workspace providers. Sensitive — stored in state. Consider using `clientSecretWo` instead. Conflicts with `clientSecretWo`.
     * 
     */
    @Export(name="clientSecret", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> clientSecret;

    /**
     * @return OAuth client secret. Required for Azure AD and Google Workspace providers. Sensitive — stored in state. Consider using `clientSecretWo` instead. Conflicts with `clientSecretWo`.
     * 
     */
    public Output<Optional<String>> clientSecret() {
        return Codegen.optional(this.clientSecret);
    }
    /**
     * **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Write-only alternative to `clientSecret`. Not stored in state. Use `clientSecretWoVersion` to trigger updates. Conflicts with `clientSecret`.
     * 
     */
    @Export(name="clientSecretWo", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> clientSecretWo;

    /**
     * @return **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
     * Write-only alternative to `clientSecret`. Not stored in state. Use `clientSecretWoVersion` to trigger updates. Conflicts with `clientSecret`.
     * 
     */
    public Output<Optional<String>> clientSecretWo() {
        return Codegen.optional(this.clientSecretWo);
    }
    /**
     * Increment to rotate `clientSecretWo` without changing the value.
     * 
     */
    @Export(name="clientSecretWoVersion", refs={Integer.class}, tree="[0]")
    private Output</* @Nullable */ Integer> clientSecretWoVersion;

    /**
     * @return Increment to rotate `clientSecretWo` without changing the value.
     * 
     */
    public Output<Optional<Integer>> clientSecretWoVersion() {
        return Codegen.optional(this.clientSecretWoVersion);
    }
    @Export(name="createdAt", refs={String.class}, tree="[0]")
    private Output<String> createdAt;

    public Output<String> createdAt() {
        return this.createdAt;
    }
    /**
     * Primary domain for the Azure AD or Google Workspace tenant.
     * 
     */
    @Export(name="domain", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> domain;

    /**
     * @return Primary domain for the Azure AD or Google Workspace tenant.
     * 
     */
    public Output<Optional<String>> domain() {
        return Codegen.optional(this.domain);
    }
    /**
     * SAML entity ID (Issuer) from your identity provider. Required for `saml` and `okta`.
     * 
     */
    @Export(name="entityId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> entityId;

    /**
     * @return SAML entity ID (Issuer) from your identity provider. Required for `saml` and `okta`.
     * 
     */
    public Output<Optional<String>> entityId() {
        return Codegen.optional(this.entityId);
    }
    /**
     * Google Workspace admin email used to fetch group memberships.
     * 
     */
    @Export(name="gsuiteAdminId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> gsuiteAdminId;

    /**
     * @return Google Workspace admin email used to fetch group memberships.
     * 
     */
    public Output<Optional<String>> gsuiteAdminId() {
        return Codegen.optional(this.gsuiteAdminId);
    }
    /**
     * Whether to include transitive (indirect) group memberships from Azure AD. Defaults to true.
     * 
     */
    @Export(name="includeIndirectGroups", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> includeIndirectGroups;

    /**
     * @return Whether to include transitive (indirect) group memberships from Azure AD. Defaults to true.
     * 
     */
    public Output<Boolean> includeIndirectGroups() {
        return this.includeIndirectGroups;
    }
    /**
     * The SSO login URL for the account, auto-generated from the slug.
     * 
     */
    @Export(name="loginUrl", refs={String.class}, tree="[0]")
    private Output<String> loginUrl;

    /**
     * @return The SSO login URL for the account, auto-generated from the slug.
     * 
     */
    public Output<String> loginUrl() {
        return this.loginUrl;
    }
    /**
     * Maximum number of Azure AD groups to fetch per user. Defaults to 250.
     * 
     */
    @Export(name="maxGroupsToRetrieve", refs={Integer.class}, tree="[0]")
    private Output<Integer> maxGroupsToRetrieve;

    /**
     * @return Maximum number of Azure AD groups to fetch per user. Defaults to 250.
     * 
     */
    public Output<Integer> maxGroupsToRetrieve() {
        return this.maxGroupsToRetrieve;
    }
    /**
     * Whether to sign SAML authentication requests. Defaults to false.
     * 
     */
    @Export(name="signRequest", refs={Boolean.class}, tree="[0]")
    private Output<Boolean> signRequest;

    /**
     * @return Whether to sign SAML authentication requests. Defaults to false.
     * 
     */
    public Output<Boolean> signRequest() {
        return this.signRequest;
    }
    /**
     * URL-safe identifier used in the SSO login URL. Auto-generated if omitted. Immutable on accounts where auto-slug enforcement is enabled.
     * 
     */
    @Export(name="slug", refs={String.class}, tree="[0]")
    private Output<String> slug;

    /**
     * @return URL-safe identifier used in the SSO login URL. Auto-generated if omitted. Immutable on accounts where auto-slug enforcement is enabled.
     * 
     */
    public Output<String> slug() {
        return this.slug;
    }
    /**
     * SAML Single Sign-On URL from your identity provider. Required for `saml` and `okta`.
     * 
     */
    @Export(name="ssoUrl", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> ssoUrl;

    /**
     * @return SAML Single Sign-On URL from your identity provider. Required for `saml` and `okta`.
     * 
     */
    public Output<Optional<String>> ssoUrl() {
        return Codegen.optional(this.ssoUrl);
    }
    /**
     * The state of the auth provider (1 = active).
     * 
     */
    @Export(name="state", refs={Integer.class}, tree="[0]")
    private Output<Integer> state;

    /**
     * @return The state of the auth provider (1 = active).
     * 
     */
    public Output<Integer> state() {
        return this.state;
    }
    /**
     * Azure AD tenant ID. Required for `azureSingleTenant`.
     * 
     */
    @Export(name="tenantId", refs={String.class}, tree="[0]")
    private Output</* @Nullable */ String> tenantId;

    /**
     * @return Azure AD tenant ID. Required for `azureSingleTenant`.
     * 
     */
    public Output<Optional<String>> tenantId() {
        return Codegen.optional(this.tenantId);
    }
    /**
     * The SSO provider type. One of: `saml`, `okta`, `gsuite`, `azureSingleTenant`, `azureMultiTenant`, `azureActiveDirectory`. Changing this value forces a new resource.
     * 
     */
    @Export(name="type", refs={String.class}, tree="[0]")
    private Output<String> type;

    /**
     * @return The SSO provider type. One of: `saml`, `okta`, `gsuite`, `azureSingleTenant`, `azureMultiTenant`, `azureActiveDirectory`. Changing this value forces a new resource.
     * 
     */
    public Output<String> type() {
        return this.type;
    }
    @Export(name="updatedAt", refs={String.class}, tree="[0]")
    private Output<String> updatedAt;

    public Output<String> updatedAt() {
        return this.updatedAt;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public AuthProvider(java.lang.String name) {
        this(name, AuthProviderArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public AuthProvider(java.lang.String name, AuthProviderArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public AuthProvider(java.lang.String name, AuthProviderArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("dbtcloud:index/authProvider:AuthProvider", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private AuthProvider(java.lang.String name, Output<java.lang.String> id, @Nullable AuthProviderState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("dbtcloud:index/authProvider:AuthProvider", name, state, makeResourceOptions(options, id), false);
    }

    private static AuthProviderArgs makeArgs(AuthProviderArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? AuthProviderArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/pulumi/pulumi-dbtcloud")
            .additionalSecretOutputs(List.of(
                "adminRefreshToken",
                "cert",
                "certWo",
                "clientSecret",
                "clientSecretWo",
                "tenantId"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static AuthProvider get(java.lang.String name, Output<java.lang.String> id, @Nullable AuthProviderState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new AuthProvider(name, id, state, options);
    }
}
