// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dbtcloud;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.dbtcloud.inputs.DatabricksSemanticLayerCredentialConfigurationArgs;
import com.pulumi.dbtcloud.inputs.DatabricksSemanticLayerCredentialCredentialArgs;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.Objects;


public final class DatabricksSemanticLayerCredentialArgs extends com.pulumi.resources.ResourceArgs {

    public static final DatabricksSemanticLayerCredentialArgs Empty = new DatabricksSemanticLayerCredentialArgs();

    /**
     * Semantic Layer credential configuration details.
     * 
     */
    @Import(name="configuration", required=true)
    private Output<DatabricksSemanticLayerCredentialConfigurationArgs> configuration;

    /**
     * @return Semantic Layer credential configuration details.
     * 
     */
    public Output<DatabricksSemanticLayerCredentialConfigurationArgs> configuration() {
        return this.configuration;
    }

    /**
     * Databricks credential details, but used in the context of the Semantic Layer.
     * 
     */
    @Import(name="credential", required=true)
    private Output<DatabricksSemanticLayerCredentialCredentialArgs> credential;

    /**
     * @return Databricks credential details, but used in the context of the Semantic Layer.
     * 
     */
    public Output<DatabricksSemanticLayerCredentialCredentialArgs> credential() {
        return this.credential;
    }

    private DatabricksSemanticLayerCredentialArgs() {}

    private DatabricksSemanticLayerCredentialArgs(DatabricksSemanticLayerCredentialArgs $) {
        this.configuration = $.configuration;
        this.credential = $.credential;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(DatabricksSemanticLayerCredentialArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private DatabricksSemanticLayerCredentialArgs $;

        public Builder() {
            $ = new DatabricksSemanticLayerCredentialArgs();
        }

        public Builder(DatabricksSemanticLayerCredentialArgs defaults) {
            $ = new DatabricksSemanticLayerCredentialArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param configuration Semantic Layer credential configuration details.
         * 
         * @return builder
         * 
         */
        public Builder configuration(Output<DatabricksSemanticLayerCredentialConfigurationArgs> configuration) {
            $.configuration = configuration;
            return this;
        }

        /**
         * @param configuration Semantic Layer credential configuration details.
         * 
         * @return builder
         * 
         */
        public Builder configuration(DatabricksSemanticLayerCredentialConfigurationArgs configuration) {
            return configuration(Output.of(configuration));
        }

        /**
         * @param credential Databricks credential details, but used in the context of the Semantic Layer.
         * 
         * @return builder
         * 
         */
        public Builder credential(Output<DatabricksSemanticLayerCredentialCredentialArgs> credential) {
            $.credential = credential;
            return this;
        }

        /**
         * @param credential Databricks credential details, but used in the context of the Semantic Layer.
         * 
         * @return builder
         * 
         */
        public Builder credential(DatabricksSemanticLayerCredentialCredentialArgs credential) {
            return credential(Output.of(credential));
        }

        public DatabricksSemanticLayerCredentialArgs build() {
            if ($.configuration == null) {
                throw new MissingRequiredPropertyException("DatabricksSemanticLayerCredentialArgs", "configuration");
            }
            if ($.credential == null) {
                throw new MissingRequiredPropertyException("DatabricksSemanticLayerCredentialArgs", "credential");
            }
            return $;
        }
    }

}
