// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dbtcloud;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PostgresCredentialArgs extends com.pulumi.resources.ResourceArgs {

    public static final PostgresCredentialArgs Empty = new PostgresCredentialArgs();

    /**
     * Default schema name
     * 
     */
    @Import(name="defaultSchema", required=true)
    private Output<String> defaultSchema;

    /**
     * @return Default schema name
     * 
     */
    public Output<String> defaultSchema() {
        return this.defaultSchema;
    }

    /**
     * Whether the Postgres/Redshift/AlloyDB credential is active
     * 
     */
    @Import(name="isActive")
    private @Nullable Output<Boolean> isActive;

    /**
     * @return Whether the Postgres/Redshift/AlloyDB credential is active
     * 
     */
    public Optional<Output<Boolean>> isActive() {
        return Optional.ofNullable(this.isActive);
    }

    /**
     * Number of threads to use
     * 
     */
    @Import(name="numThreads")
    private @Nullable Output<Integer> numThreads;

    /**
     * @return Number of threads to use
     * 
     */
    public Optional<Output<Integer>> numThreads() {
        return Optional.ofNullable(this.numThreads);
    }

    /**
     * Password for Postgres/Redshift/AlloyDB
     * 
     */
    @Import(name="password")
    private @Nullable Output<String> password;

    /**
     * @return Password for Postgres/Redshift/AlloyDB
     * 
     */
    public Optional<Output<String>> password() {
        return Optional.ofNullable(this.password);
    }

    /**
     * Project ID to create the Postgres/Redshift/AlloyDB credential in
     * 
     */
    @Import(name="projectId", required=true)
    private Output<Integer> projectId;

    /**
     * @return Project ID to create the Postgres/Redshift/AlloyDB credential in
     * 
     */
    public Output<Integer> projectId() {
        return this.projectId;
    }

    /**
     * Default schema name
     * 
     */
    @Import(name="targetName")
    private @Nullable Output<String> targetName;

    /**
     * @return Default schema name
     * 
     */
    public Optional<Output<String>> targetName() {
        return Optional.ofNullable(this.targetName);
    }

    /**
     * Type of connection. One of (postgres/redshift). Use postgres for alloydb connections
     * 
     */
    @Import(name="type", required=true)
    private Output<String> type;

    /**
     * @return Type of connection. One of (postgres/redshift). Use postgres for alloydb connections
     * 
     */
    public Output<String> type() {
        return this.type;
    }

    /**
     * Username for Postgres/Redshift/AlloyDB
     * 
     */
    @Import(name="username", required=true)
    private Output<String> username;

    /**
     * @return Username for Postgres/Redshift/AlloyDB
     * 
     */
    public Output<String> username() {
        return this.username;
    }

    private PostgresCredentialArgs() {}

    private PostgresCredentialArgs(PostgresCredentialArgs $) {
        this.defaultSchema = $.defaultSchema;
        this.isActive = $.isActive;
        this.numThreads = $.numThreads;
        this.password = $.password;
        this.projectId = $.projectId;
        this.targetName = $.targetName;
        this.type = $.type;
        this.username = $.username;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PostgresCredentialArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PostgresCredentialArgs $;

        public Builder() {
            $ = new PostgresCredentialArgs();
        }

        public Builder(PostgresCredentialArgs defaults) {
            $ = new PostgresCredentialArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param defaultSchema Default schema name
         * 
         * @return builder
         * 
         */
        public Builder defaultSchema(Output<String> defaultSchema) {
            $.defaultSchema = defaultSchema;
            return this;
        }

        /**
         * @param defaultSchema Default schema name
         * 
         * @return builder
         * 
         */
        public Builder defaultSchema(String defaultSchema) {
            return defaultSchema(Output.of(defaultSchema));
        }

        /**
         * @param isActive Whether the Postgres/Redshift/AlloyDB credential is active
         * 
         * @return builder
         * 
         */
        public Builder isActive(@Nullable Output<Boolean> isActive) {
            $.isActive = isActive;
            return this;
        }

        /**
         * @param isActive Whether the Postgres/Redshift/AlloyDB credential is active
         * 
         * @return builder
         * 
         */
        public Builder isActive(Boolean isActive) {
            return isActive(Output.of(isActive));
        }

        /**
         * @param numThreads Number of threads to use
         * 
         * @return builder
         * 
         */
        public Builder numThreads(@Nullable Output<Integer> numThreads) {
            $.numThreads = numThreads;
            return this;
        }

        /**
         * @param numThreads Number of threads to use
         * 
         * @return builder
         * 
         */
        public Builder numThreads(Integer numThreads) {
            return numThreads(Output.of(numThreads));
        }

        /**
         * @param password Password for Postgres/Redshift/AlloyDB
         * 
         * @return builder
         * 
         */
        public Builder password(@Nullable Output<String> password) {
            $.password = password;
            return this;
        }

        /**
         * @param password Password for Postgres/Redshift/AlloyDB
         * 
         * @return builder
         * 
         */
        public Builder password(String password) {
            return password(Output.of(password));
        }

        /**
         * @param projectId Project ID to create the Postgres/Redshift/AlloyDB credential in
         * 
         * @return builder
         * 
         */
        public Builder projectId(Output<Integer> projectId) {
            $.projectId = projectId;
            return this;
        }

        /**
         * @param projectId Project ID to create the Postgres/Redshift/AlloyDB credential in
         * 
         * @return builder
         * 
         */
        public Builder projectId(Integer projectId) {
            return projectId(Output.of(projectId));
        }

        /**
         * @param targetName Default schema name
         * 
         * @return builder
         * 
         */
        public Builder targetName(@Nullable Output<String> targetName) {
            $.targetName = targetName;
            return this;
        }

        /**
         * @param targetName Default schema name
         * 
         * @return builder
         * 
         */
        public Builder targetName(String targetName) {
            return targetName(Output.of(targetName));
        }

        /**
         * @param type Type of connection. One of (postgres/redshift). Use postgres for alloydb connections
         * 
         * @return builder
         * 
         */
        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type Type of connection. One of (postgres/redshift). Use postgres for alloydb connections
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        /**
         * @param username Username for Postgres/Redshift/AlloyDB
         * 
         * @return builder
         * 
         */
        public Builder username(Output<String> username) {
            $.username = username;
            return this;
        }

        /**
         * @param username Username for Postgres/Redshift/AlloyDB
         * 
         * @return builder
         * 
         */
        public Builder username(String username) {
            return username(Output.of(username));
        }

        public PostgresCredentialArgs build() {
            if ($.defaultSchema == null) {
                throw new MissingRequiredPropertyException("PostgresCredentialArgs", "defaultSchema");
            }
            if ($.projectId == null) {
                throw new MissingRequiredPropertyException("PostgresCredentialArgs", "projectId");
            }
            if ($.type == null) {
                throw new MissingRequiredPropertyException("PostgresCredentialArgs", "type");
            }
            if ($.username == null) {
                throw new MissingRequiredPropertyException("PostgresCredentialArgs", "username");
            }
            return $;
        }
    }

}
