// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dbtcloud;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.dbtcloud.ProjectConnectionArgs;
import com.pulumi.dbtcloud.Utilities;
import com.pulumi.dbtcloud.inputs.ProjectConnectionState;
import java.lang.Integer;
import javax.annotation.Nullable;

/**
 * &gt; This resource is deprecated with the release of global connections and it will be removed in a future version of the provider. Going forward, please set the `connection_id` in the `dbtcloud.Environment` resource instead.
 * 
 * ## Example Usage
 * 
 * &lt;!--Start PulumiCodeChooser --&gt;
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.dbtcloud.ProjectConnection;
 * import com.pulumi.dbtcloud.ProjectConnectionArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var dbtProjectConnection = new ProjectConnection("dbtProjectConnection", ProjectConnectionArgs.builder()
 *             .projectId(dbtProject.id())
 *             .connectionId(dbtConnection.connectionId())
 *             .build());
 * 
 *     }
 * }
 * }
 * </pre>
 * &lt;!--End PulumiCodeChooser --&gt;
 * 
 * ## Import
 * 
 * using  import blocks (requires Terraform &gt;= 1.5)
 * 
 * import {
 * 
 *   to = dbtcloud_project_connection.my_project
 * 
 *   id = &#34;project_id:connection_id&#34;
 * 
 * }
 * 
 * import {
 * 
 *   to = dbtcloud_project_connection.my_project
 * 
 *   id = &#34;12345:5678&#34;
 * 
 * }
 * 
 * using the older import command
 * 
 * ```sh
 * $ pulumi import dbtcloud:index/projectConnection:ProjectConnection my_project &#34;project_id:connection_id&#34;
 * ```
 * 
 * ```sh
 * $ pulumi import dbtcloud:index/projectConnection:ProjectConnection my_project 12345:5678
 * ```
 * 
 */
@ResourceType(type="dbtcloud:index/projectConnection:ProjectConnection")
public class ProjectConnection extends com.pulumi.resources.CustomResource {
    /**
     * Connection ID
     * 
     */
    @Export(name="connectionId", refs={Integer.class}, tree="[0]")
    private Output<Integer> connectionId;

    /**
     * @return Connection ID
     * 
     */
    public Output<Integer> connectionId() {
        return this.connectionId;
    }
    /**
     * Project ID
     * 
     */
    @Export(name="projectId", refs={Integer.class}, tree="[0]")
    private Output<Integer> projectId;

    /**
     * @return Project ID
     * 
     */
    public Output<Integer> projectId() {
        return this.projectId;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public ProjectConnection(java.lang.String name) {
        this(name, ProjectConnectionArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public ProjectConnection(java.lang.String name, ProjectConnectionArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public ProjectConnection(java.lang.String name, ProjectConnectionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("dbtcloud:index/projectConnection:ProjectConnection", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private ProjectConnection(java.lang.String name, Output<java.lang.String> id, @Nullable ProjectConnectionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("dbtcloud:index/projectConnection:ProjectConnection", name, state, makeResourceOptions(options, id), false);
    }

    private static ProjectConnectionArgs makeArgs(ProjectConnectionArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? ProjectConnectionArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/pulumi/pulumi-dbtcloud")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static ProjectConnection get(java.lang.String name, Output<java.lang.String> id, @Nullable ProjectConnectionState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new ProjectConnection(name, id, state, options);
    }
}
