// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dbtcloud;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.dbtcloud.SalesforceCredentialArgs;
import com.pulumi.dbtcloud.Utilities;
import com.pulumi.dbtcloud.inputs.SalesforceCredentialState;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import javax.annotation.Nullable;

/**
 * Salesforce credential resource
 * 
 * ## Example Usage
 * 
 * <pre>
 * {@code
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.dbtcloud.SalesforceCredential;
 * import com.pulumi.dbtcloud.SalesforceCredentialArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App }{{@code
 *     public static void main(String[] args) }{{@code
 *         Pulumi.run(App::stack);
 *     }}{@code
 * 
 *     public static void stack(Context ctx) }{{@code
 *         // Create a Salesforce credential for dbt Cloud using JWT Bearer Flow authentication
 *         var mySalesforceCred = new SalesforceCredential("mySalesforceCred", SalesforceCredentialArgs.builder()
 *             .projectId(dbtProject.id())
 *             .username("user}{@literal @}{@code example.com")
 *             .clientId("your-oauth-client-id")
 *             .privateKey("private-key value")
 *             .targetName("default")
 *             .numThreads(6)
 *             .build());
 * 
 *     }}{@code
 * }}{@code
 * }
 * </pre>
 * 
 * ## Import
 * 
 * using  import blocks (requires Terraform &gt;= 1.5)
 * import {
 * to = dbtcloud_salesforce_credential.my_salesforce_credential
 * id = &#34;project_id:credential_id&#34;
 * }
 * 
 * import {
 * to = dbtcloud_salesforce_credential.my_salesforce_credential
 * id = &#34;12345:6789&#34;
 * }
 * 
 * using the older import command
 * 
 * ```sh
 * $ pulumi import dbtcloud:index/salesforceCredential:SalesforceCredential my_salesforce_credential &#34;project_id:credential_id&#34;
 * $ pulumi import dbtcloud:index/salesforceCredential:SalesforceCredential my_salesforce_credential 12345:6789
 * ```
 * 
 */
@ResourceType(type="dbtcloud:index/salesforceCredential:SalesforceCredential")
public class SalesforceCredential extends com.pulumi.resources.CustomResource {
    /**
     * The OAuth connected app client/consumer ID
     * 
     */
    @Export(name="clientId", refs={String.class}, tree="[0]")
    private Output<String> clientId;

    /**
     * @return The OAuth connected app client/consumer ID
     * 
     */
    public Output<String> clientId() {
        return this.clientId;
    }
    /**
     * The system Salesforce credential ID
     * 
     */
    @Export(name="credentialId", refs={Integer.class}, tree="[0]")
    private Output<Integer> credentialId;

    /**
     * @return The system Salesforce credential ID
     * 
     */
    public Output<Integer> credentialId() {
        return this.credentialId;
    }
    /**
     * The number of threads to use for dbt operations
     * 
     */
    @Export(name="numThreads", refs={Integer.class}, tree="[0]")
    private Output<Integer> numThreads;

    /**
     * @return The number of threads to use for dbt operations
     * 
     */
    public Output<Integer> numThreads() {
        return this.numThreads;
    }
    /**
     * The private key for JWT bearer flow authentication
     * 
     */
    @Export(name="privateKey", refs={String.class}, tree="[0]")
    private Output<String> privateKey;

    /**
     * @return The private key for JWT bearer flow authentication
     * 
     */
    public Output<String> privateKey() {
        return this.privateKey;
    }
    /**
     * Project ID to create the Salesforce credential in
     * 
     */
    @Export(name="projectId", refs={Integer.class}, tree="[0]")
    private Output<Integer> projectId;

    /**
     * @return Project ID to create the Salesforce credential in
     * 
     */
    public Output<Integer> projectId() {
        return this.projectId;
    }
    /**
     * Target name
     * 
     */
    @Export(name="targetName", refs={String.class}, tree="[0]")
    private Output<String> targetName;

    /**
     * @return Target name
     * 
     */
    public Output<String> targetName() {
        return this.targetName;
    }
    /**
     * The Salesforce username for OAuth JWT bearer flow authentication
     * 
     */
    @Export(name="username", refs={String.class}, tree="[0]")
    private Output<String> username;

    /**
     * @return The Salesforce username for OAuth JWT bearer flow authentication
     * 
     */
    public Output<String> username() {
        return this.username;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public SalesforceCredential(java.lang.String name) {
        this(name, SalesforceCredentialArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public SalesforceCredential(java.lang.String name, SalesforceCredentialArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public SalesforceCredential(java.lang.String name, SalesforceCredentialArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("dbtcloud:index/salesforceCredential:SalesforceCredential", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private SalesforceCredential(java.lang.String name, Output<java.lang.String> id, @Nullable SalesforceCredentialState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("dbtcloud:index/salesforceCredential:SalesforceCredential", name, state, makeResourceOptions(options, id), false);
    }

    private static SalesforceCredentialArgs makeArgs(SalesforceCredentialArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? SalesforceCredentialArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/pulumi/pulumi-dbtcloud")
            .additionalSecretOutputs(List.of(
                "clientId",
                "privateKey"
            ))
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static SalesforceCredential get(java.lang.String name, Output<java.lang.String> id, @Nullable SalesforceCredentialState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new SalesforceCredential(name, id, state, options);
    }
}
