// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dbtcloud;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class SalesforceCredentialArgs extends com.pulumi.resources.ResourceArgs {

    public static final SalesforceCredentialArgs Empty = new SalesforceCredentialArgs();

    /**
     * The OAuth connected app client/consumer ID
     * 
     */
    @Import(name="clientId", required=true)
    private Output<String> clientId;

    /**
     * @return The OAuth connected app client/consumer ID
     * 
     */
    public Output<String> clientId() {
        return this.clientId;
    }

    /**
     * The number of threads to use for dbt operations
     * 
     */
    @Import(name="numThreads")
    private @Nullable Output<Integer> numThreads;

    /**
     * @return The number of threads to use for dbt operations
     * 
     */
    public Optional<Output<Integer>> numThreads() {
        return Optional.ofNullable(this.numThreads);
    }

    /**
     * The private key for JWT bearer flow authentication
     * 
     */
    @Import(name="privateKey", required=true)
    private Output<String> privateKey;

    /**
     * @return The private key for JWT bearer flow authentication
     * 
     */
    public Output<String> privateKey() {
        return this.privateKey;
    }

    /**
     * Project ID to create the Salesforce credential in
     * 
     */
    @Import(name="projectId", required=true)
    private Output<Integer> projectId;

    /**
     * @return Project ID to create the Salesforce credential in
     * 
     */
    public Output<Integer> projectId() {
        return this.projectId;
    }

    /**
     * Target name
     * 
     */
    @Import(name="targetName")
    private @Nullable Output<String> targetName;

    /**
     * @return Target name
     * 
     */
    public Optional<Output<String>> targetName() {
        return Optional.ofNullable(this.targetName);
    }

    /**
     * The Salesforce username for OAuth JWT bearer flow authentication
     * 
     */
    @Import(name="username", required=true)
    private Output<String> username;

    /**
     * @return The Salesforce username for OAuth JWT bearer flow authentication
     * 
     */
    public Output<String> username() {
        return this.username;
    }

    private SalesforceCredentialArgs() {}

    private SalesforceCredentialArgs(SalesforceCredentialArgs $) {
        this.clientId = $.clientId;
        this.numThreads = $.numThreads;
        this.privateKey = $.privateKey;
        this.projectId = $.projectId;
        this.targetName = $.targetName;
        this.username = $.username;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(SalesforceCredentialArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private SalesforceCredentialArgs $;

        public Builder() {
            $ = new SalesforceCredentialArgs();
        }

        public Builder(SalesforceCredentialArgs defaults) {
            $ = new SalesforceCredentialArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param clientId The OAuth connected app client/consumer ID
         * 
         * @return builder
         * 
         */
        public Builder clientId(Output<String> clientId) {
            $.clientId = clientId;
            return this;
        }

        /**
         * @param clientId The OAuth connected app client/consumer ID
         * 
         * @return builder
         * 
         */
        public Builder clientId(String clientId) {
            return clientId(Output.of(clientId));
        }

        /**
         * @param numThreads The number of threads to use for dbt operations
         * 
         * @return builder
         * 
         */
        public Builder numThreads(@Nullable Output<Integer> numThreads) {
            $.numThreads = numThreads;
            return this;
        }

        /**
         * @param numThreads The number of threads to use for dbt operations
         * 
         * @return builder
         * 
         */
        public Builder numThreads(Integer numThreads) {
            return numThreads(Output.of(numThreads));
        }

        /**
         * @param privateKey The private key for JWT bearer flow authentication
         * 
         * @return builder
         * 
         */
        public Builder privateKey(Output<String> privateKey) {
            $.privateKey = privateKey;
            return this;
        }

        /**
         * @param privateKey The private key for JWT bearer flow authentication
         * 
         * @return builder
         * 
         */
        public Builder privateKey(String privateKey) {
            return privateKey(Output.of(privateKey));
        }

        /**
         * @param projectId Project ID to create the Salesforce credential in
         * 
         * @return builder
         * 
         */
        public Builder projectId(Output<Integer> projectId) {
            $.projectId = projectId;
            return this;
        }

        /**
         * @param projectId Project ID to create the Salesforce credential in
         * 
         * @return builder
         * 
         */
        public Builder projectId(Integer projectId) {
            return projectId(Output.of(projectId));
        }

        /**
         * @param targetName Target name
         * 
         * @return builder
         * 
         */
        public Builder targetName(@Nullable Output<String> targetName) {
            $.targetName = targetName;
            return this;
        }

        /**
         * @param targetName Target name
         * 
         * @return builder
         * 
         */
        public Builder targetName(String targetName) {
            return targetName(Output.of(targetName));
        }

        /**
         * @param username The Salesforce username for OAuth JWT bearer flow authentication
         * 
         * @return builder
         * 
         */
        public Builder username(Output<String> username) {
            $.username = username;
            return this;
        }

        /**
         * @param username The Salesforce username for OAuth JWT bearer flow authentication
         * 
         * @return builder
         * 
         */
        public Builder username(String username) {
            return username(Output.of(username));
        }

        public SalesforceCredentialArgs build() {
            if ($.clientId == null) {
                throw new MissingRequiredPropertyException("SalesforceCredentialArgs", "clientId");
            }
            if ($.privateKey == null) {
                throw new MissingRequiredPropertyException("SalesforceCredentialArgs", "privateKey");
            }
            if ($.projectId == null) {
                throw new MissingRequiredPropertyException("SalesforceCredentialArgs", "projectId");
            }
            if ($.username == null) {
                throw new MissingRequiredPropertyException("SalesforceCredentialArgs", "username");
            }
            return $;
        }
    }

}
