// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dbtcloud;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.util.Objects;


public final class ScimConfigArgs extends com.pulumi.resources.ResourceArgs {

    public static final ScimConfigArgs Empty = new ScimConfigArgs();

    /**
     * Whether SCIM provisioning is enabled for the account.
     * 
     */
    @Import(name="enabled", required=true)
    private Output<Boolean> enabled;

    /**
     * @return Whether SCIM provisioning is enabled for the account.
     * 
     */
    public Output<Boolean> enabled() {
        return this.enabled;
    }

    /**
     * Whether administrators can manually update users and groups that are managed by SCIM. When set to ~~~false~~~, SCIM is the sole source of truth for user and group management.
     * 
     */
    @Import(name="manualUpdatesAllowed", required=true)
    private Output<Boolean> manualUpdatesAllowed;

    /**
     * @return Whether administrators can manually update users and groups that are managed by SCIM. When set to ~~~false~~~, SCIM is the sole source of truth for user and group management.
     * 
     */
    public Output<Boolean> manualUpdatesAllowed() {
        return this.manualUpdatesAllowed;
    }

    /**
     * Whether the dbt Cloud license type (Developer, Read-Only, IT) is controlled by SCIM attribute mapping. When set to ~~~false~~~, license types are managed manually inside dbt Cloud.
     * 
     */
    @Import(name="scimControlledLicenseType", required=true)
    private Output<Boolean> scimControlledLicenseType;

    /**
     * @return Whether the dbt Cloud license type (Developer, Read-Only, IT) is controlled by SCIM attribute mapping. When set to ~~~false~~~, license types are managed manually inside dbt Cloud.
     * 
     */
    public Output<Boolean> scimControlledLicenseType() {
        return this.scimControlledLicenseType;
    }

    private ScimConfigArgs() {}

    private ScimConfigArgs(ScimConfigArgs $) {
        this.enabled = $.enabled;
        this.manualUpdatesAllowed = $.manualUpdatesAllowed;
        this.scimControlledLicenseType = $.scimControlledLicenseType;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ScimConfigArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ScimConfigArgs $;

        public Builder() {
            $ = new ScimConfigArgs();
        }

        public Builder(ScimConfigArgs defaults) {
            $ = new ScimConfigArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param enabled Whether SCIM provisioning is enabled for the account.
         * 
         * @return builder
         * 
         */
        public Builder enabled(Output<Boolean> enabled) {
            $.enabled = enabled;
            return this;
        }

        /**
         * @param enabled Whether SCIM provisioning is enabled for the account.
         * 
         * @return builder
         * 
         */
        public Builder enabled(Boolean enabled) {
            return enabled(Output.of(enabled));
        }

        /**
         * @param manualUpdatesAllowed Whether administrators can manually update users and groups that are managed by SCIM. When set to ~~~false~~~, SCIM is the sole source of truth for user and group management.
         * 
         * @return builder
         * 
         */
        public Builder manualUpdatesAllowed(Output<Boolean> manualUpdatesAllowed) {
            $.manualUpdatesAllowed = manualUpdatesAllowed;
            return this;
        }

        /**
         * @param manualUpdatesAllowed Whether administrators can manually update users and groups that are managed by SCIM. When set to ~~~false~~~, SCIM is the sole source of truth for user and group management.
         * 
         * @return builder
         * 
         */
        public Builder manualUpdatesAllowed(Boolean manualUpdatesAllowed) {
            return manualUpdatesAllowed(Output.of(manualUpdatesAllowed));
        }

        /**
         * @param scimControlledLicenseType Whether the dbt Cloud license type (Developer, Read-Only, IT) is controlled by SCIM attribute mapping. When set to ~~~false~~~, license types are managed manually inside dbt Cloud.
         * 
         * @return builder
         * 
         */
        public Builder scimControlledLicenseType(Output<Boolean> scimControlledLicenseType) {
            $.scimControlledLicenseType = scimControlledLicenseType;
            return this;
        }

        /**
         * @param scimControlledLicenseType Whether the dbt Cloud license type (Developer, Read-Only, IT) is controlled by SCIM attribute mapping. When set to ~~~false~~~, license types are managed manually inside dbt Cloud.
         * 
         * @return builder
         * 
         */
        public Builder scimControlledLicenseType(Boolean scimControlledLicenseType) {
            return scimControlledLicenseType(Output.of(scimControlledLicenseType));
        }

        public ScimConfigArgs build() {
            if ($.enabled == null) {
                throw new MissingRequiredPropertyException("ScimConfigArgs", "enabled");
            }
            if ($.manualUpdatesAllowed == null) {
                throw new MissingRequiredPropertyException("ScimConfigArgs", "manualUpdatesAllowed");
            }
            if ($.scimControlledLicenseType == null) {
                throw new MissingRequiredPropertyException("ScimConfigArgs", "scimControlledLicenseType");
            }
            return $;
        }
    }

}
