provider: dbtcloud
major-version: 1
makeTemplate: bridged
generate-nightly-test-workflow: true
providerDefaultBranch: main
plugins:
  - name: std
    version: "1.6.2"
  - name: terraform
    version: "1.0.16"
    kind: converter
license:
  ignore:
    # This project does have a LISCENCE, but it's not of the standard format. It is Apache-2.0.
    - github.com/oapi-codegen/nullable
# Use `pulumi convert` for translating examples from TF to Pulumi.
pulumiConvert: 1
registryDocs: true
integrationTestProvider: true
esc:
  enabled: true
