provider: dbtcloud
major-version: 1
makeTemplate: bridged
generate-nightly-test-workflow: true
providerDefaultBranch: main
license:
    ignore:
        # This project does have a LISCENCE, but it's not of the standard format. It is Apache-2.0.
        - github.com/oapi-codegen/nullable
# Use `pulumi convert` for translating examples from TF to Pulumi.
pulumiConvert: 1
registryDocs: true
integrationTestProvider: true
esc:
    enabled: true
    environment: imports/github-secrets # No repo-specific secrets.
