// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DbtCloud
{
    /// <summary>
    /// Resource to manage dbt Cloud environments for the different dbt Cloud projects. In a given dbt Cloud project, one development environment can be defined and as many deployment environments as needed can be created. &gt; In August 2024, dbt Cloud released the "global connection" feature, allowing connections to be defined at the account level and reused across environments and projects. This version of the provider has the ConnectionId as an optional field but it is recommended to start setting it up in your projects. In future versions, this field will become mandatory.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using DbtCloud = Pulumi.DbtCloud;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var ciEnvironment = new DbtCloud.Environment("ci_environment", new()
    ///     {
    ///         DbtVersion = "latest",
    ///         Name = "CI",
    ///         ProjectId = dbtProject.Id,
    ///         Type = "deployment",
    ///         CredentialId = ciCredential.CredentialId,
    ///         ConnectionId = myGlobalConnection.Id,
    ///     });
    /// 
    ///     // we can also set a deployment environment as being the production one
    ///     var prodEnvironment = new DbtCloud.Environment("prod_environment", new()
    ///     {
    ///         DbtVersion = "1.7.0-latest",
    ///         Name = "Prod",
    ///         ProjectId = dbtProject.Id,
    ///         Type = "deployment",
    ///         CredentialId = prodCredential.CredentialId,
    ///         DeploymentType = "production",
    ///         ConnectionId = myLegacyConnection.ConnectionId,
    ///     });
    /// 
    ///     // Creating a development environment
    ///     var devEnvironment = new DbtCloud.Environment("dev_environment", new()
    ///     {
    ///         DbtVersion = "latest",
    ///         Name = "Dev",
    ///         ProjectId = dbtProject.Id,
    ///         Type = "development",
    ///         ConnectionId = myOtherGlobalConnection.Id,
    ///     });
    /// 
    ///     // Deployment environment with a primary profile (binds connection + credentials via profile)
    ///     // NOTE: avoid setting connection_id, credential_id, or extended_attributes_id alongside
    ///     // primary_profile_id — dbt Cloud may propagate the environment's values onto the profile,
    ///     // overwriting the profile's own settings and affecting other environments sharing that profile.
    ///     var profiledEnvironment = new DbtCloud.Environment("profiled_environment", new()
    ///     {
    ///         DbtVersion = "latest",
    ///         Name = "Staging",
    ///         ProjectId = dbtProject.Id,
    ///         Type = "deployment",
    ///         DeploymentType = "staging",
    ///         PrimaryProfileId = myProfile.ProfileId,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// using  import blocks (requires Terraform &gt;= 1.5)
    /// import {
    /// to = dbtcloud_environment.prod_environment
    /// id = "project_id:environment_id"
    /// }
    /// 
    /// import {
    /// to = dbtcloud_environment.prod_environment
    /// id = "12345:6789"
    /// }
    /// 
    /// using the older import command
    /// 
    /// ```sh
    /// $ pulumi import dbtcloud:index/environment:Environment prod_environment "project_id:environment_id"
    /// $ pulumi import dbtcloud:index/environment:Environment prod_environment 12345:6789
    /// ```
    /// </summary>
    [DbtCloudResourceType("dbtcloud:index/environment:Environment")]
    public partial class Environment : global::Pulumi.CustomResource
    {
        /// <summary>
        /// A connection ID (used with Global Connections)
        /// </summary>
        [Output("connectionId")]
        public Output<int> ConnectionId { get; private set; } = null!;

        /// <summary>
        /// The Credential ID for this environment. A credential is not actionable for development environments, as users have to set their own development credentials in dbt Cloud.
        /// </summary>
        [Output("credentialId")]
        public Output<int> CredentialId { get; private set; } = null!;

        /// <summary>
        /// The custom branch name to use
        /// </summary>
        [Output("customBranch")]
        public Output<string?> CustomBranch { get; private set; } = null!;

        /// <summary>
        /// Version number of dbt to use in this environment. It needs to be in the format `major.minor.0-latest` (e.g. `1.5.0-latest`), `major.minor.0-pre`, `Compatible`, `Extended`, `Versionless`, `Latest` or `latest-fusion`. While `Versionless` is still supported, using `Latest` is recommended. Defaults to `Latest` if no version is provided
        /// </summary>
        [Output("dbtVersion")]
        public Output<string> DbtVersion { get; private set; } = null!;

        /// <summary>
        /// The type of environment. Only valid for environments of type 'deployment' and for now can only be 'production', 'staging' or left empty for generic environments
        /// </summary>
        [Output("deploymentType")]
        public Output<string?> DeploymentType { get; private set; } = null!;

        /// <summary>
        /// Whether to enable model query history in this environment. As of Oct 2024, works only for Snowflake and BigQuery.
        /// </summary>
        [Output("enableModelQueryHistory")]
        public Output<bool> EnableModelQueryHistory { get; private set; } = null!;

        /// <summary>
        /// The ID of the environment. Duplicated. Here for backward compatibility.
        /// </summary>
        [Output("environmentId")]
        public Output<int> EnvironmentId { get; private set; } = null!;

        /// <summary>
        /// The ID of the extended attributes applied
        /// </summary>
        [Output("extendedAttributesId")]
        public Output<int> ExtendedAttributesId { get; private set; } = null!;

        /// <summary>
        /// Whether the environment is active
        /// </summary>
        [Output("isActive")]
        public Output<bool> IsActive { get; private set; } = null!;

        /// <summary>
        /// The name of the environment
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The ID of the primary profile for this environment. A profile ties together a connection and credentials. Only applicable to deployment environments. &gt; Setting `PrimaryProfileId` alongside `ConnectionId`, `CredentialId`, or `ExtendedAttributesId` will produce an error. When a profile is assigned, the API determines those values from the profile. Manage connection, credentials, and extended attributes through the `dbtcloud.Profile` resource instead.
        /// </summary>
        [Output("primaryProfileId")]
        public Output<int> PrimaryProfileId { get; private set; } = null!;

        /// <summary>
        /// Project ID to create the environment in
        /// </summary>
        [Output("projectId")]
        public Output<int> ProjectId { get; private set; } = null!;

        /// <summary>
        /// The type of environment (must be either development or deployment)
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;

        /// <summary>
        /// Whether to use a custom git branch in this environment
        /// </summary>
        [Output("useCustomBranch")]
        public Output<bool> UseCustomBranch { get; private set; } = null!;


        /// <summary>
        /// Create a Environment resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Environment(string name, EnvironmentArgs args, CustomResourceOptions? options = null)
            : base("dbtcloud:index/environment:Environment", name, args ?? new EnvironmentArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Environment(string name, Input<string> id, EnvironmentState? state = null, CustomResourceOptions? options = null)
            : base("dbtcloud:index/environment:Environment", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumi/pulumi-dbtcloud",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Environment resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Environment Get(string name, Input<string> id, EnvironmentState? state = null, CustomResourceOptions? options = null)
        {
            return new Environment(name, id, state, options);
        }
    }

    public sealed class EnvironmentArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A connection ID (used with Global Connections)
        /// </summary>
        [Input("connectionId")]
        public Input<int>? ConnectionId { get; set; }

        /// <summary>
        /// The Credential ID for this environment. A credential is not actionable for development environments, as users have to set their own development credentials in dbt Cloud.
        /// </summary>
        [Input("credentialId")]
        public Input<int>? CredentialId { get; set; }

        /// <summary>
        /// The custom branch name to use
        /// </summary>
        [Input("customBranch")]
        public Input<string>? CustomBranch { get; set; }

        /// <summary>
        /// Version number of dbt to use in this environment. It needs to be in the format `major.minor.0-latest` (e.g. `1.5.0-latest`), `major.minor.0-pre`, `Compatible`, `Extended`, `Versionless`, `Latest` or `latest-fusion`. While `Versionless` is still supported, using `Latest` is recommended. Defaults to `Latest` if no version is provided
        /// </summary>
        [Input("dbtVersion")]
        public Input<string>? DbtVersion { get; set; }

        /// <summary>
        /// The type of environment. Only valid for environments of type 'deployment' and for now can only be 'production', 'staging' or left empty for generic environments
        /// </summary>
        [Input("deploymentType")]
        public Input<string>? DeploymentType { get; set; }

        /// <summary>
        /// Whether to enable model query history in this environment. As of Oct 2024, works only for Snowflake and BigQuery.
        /// </summary>
        [Input("enableModelQueryHistory")]
        public Input<bool>? EnableModelQueryHistory { get; set; }

        /// <summary>
        /// The ID of the extended attributes applied
        /// </summary>
        [Input("extendedAttributesId")]
        public Input<int>? ExtendedAttributesId { get; set; }

        /// <summary>
        /// Whether the environment is active
        /// </summary>
        [Input("isActive")]
        public Input<bool>? IsActive { get; set; }

        /// <summary>
        /// The name of the environment
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The ID of the primary profile for this environment. A profile ties together a connection and credentials. Only applicable to deployment environments. &gt; Setting `PrimaryProfileId` alongside `ConnectionId`, `CredentialId`, or `ExtendedAttributesId` will produce an error. When a profile is assigned, the API determines those values from the profile. Manage connection, credentials, and extended attributes through the `dbtcloud.Profile` resource instead.
        /// </summary>
        [Input("primaryProfileId")]
        public Input<int>? PrimaryProfileId { get; set; }

        /// <summary>
        /// Project ID to create the environment in
        /// </summary>
        [Input("projectId", required: true)]
        public Input<int> ProjectId { get; set; } = null!;

        /// <summary>
        /// The type of environment (must be either development or deployment)
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        /// <summary>
        /// Whether to use a custom git branch in this environment
        /// </summary>
        [Input("useCustomBranch")]
        public Input<bool>? UseCustomBranch { get; set; }

        public EnvironmentArgs()
        {
        }
        public static new EnvironmentArgs Empty => new EnvironmentArgs();
    }

    public sealed class EnvironmentState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A connection ID (used with Global Connections)
        /// </summary>
        [Input("connectionId")]
        public Input<int>? ConnectionId { get; set; }

        /// <summary>
        /// The Credential ID for this environment. A credential is not actionable for development environments, as users have to set their own development credentials in dbt Cloud.
        /// </summary>
        [Input("credentialId")]
        public Input<int>? CredentialId { get; set; }

        /// <summary>
        /// The custom branch name to use
        /// </summary>
        [Input("customBranch")]
        public Input<string>? CustomBranch { get; set; }

        /// <summary>
        /// Version number of dbt to use in this environment. It needs to be in the format `major.minor.0-latest` (e.g. `1.5.0-latest`), `major.minor.0-pre`, `Compatible`, `Extended`, `Versionless`, `Latest` or `latest-fusion`. While `Versionless` is still supported, using `Latest` is recommended. Defaults to `Latest` if no version is provided
        /// </summary>
        [Input("dbtVersion")]
        public Input<string>? DbtVersion { get; set; }

        /// <summary>
        /// The type of environment. Only valid for environments of type 'deployment' and for now can only be 'production', 'staging' or left empty for generic environments
        /// </summary>
        [Input("deploymentType")]
        public Input<string>? DeploymentType { get; set; }

        /// <summary>
        /// Whether to enable model query history in this environment. As of Oct 2024, works only for Snowflake and BigQuery.
        /// </summary>
        [Input("enableModelQueryHistory")]
        public Input<bool>? EnableModelQueryHistory { get; set; }

        /// <summary>
        /// The ID of the environment. Duplicated. Here for backward compatibility.
        /// </summary>
        [Input("environmentId")]
        public Input<int>? EnvironmentId { get; set; }

        /// <summary>
        /// The ID of the extended attributes applied
        /// </summary>
        [Input("extendedAttributesId")]
        public Input<int>? ExtendedAttributesId { get; set; }

        /// <summary>
        /// Whether the environment is active
        /// </summary>
        [Input("isActive")]
        public Input<bool>? IsActive { get; set; }

        /// <summary>
        /// The name of the environment
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The ID of the primary profile for this environment. A profile ties together a connection and credentials. Only applicable to deployment environments. &gt; Setting `PrimaryProfileId` alongside `ConnectionId`, `CredentialId`, or `ExtendedAttributesId` will produce an error. When a profile is assigned, the API determines those values from the profile. Manage connection, credentials, and extended attributes through the `dbtcloud.Profile` resource instead.
        /// </summary>
        [Input("primaryProfileId")]
        public Input<int>? PrimaryProfileId { get; set; }

        /// <summary>
        /// Project ID to create the environment in
        /// </summary>
        [Input("projectId")]
        public Input<int>? ProjectId { get; set; }

        /// <summary>
        /// The type of environment (must be either development or deployment)
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        /// <summary>
        /// Whether to use a custom git branch in this environment
        /// </summary>
        [Input("useCustomBranch")]
        public Input<bool>? UseCustomBranch { get; set; }

        public EnvironmentState()
        {
        }
        public static new EnvironmentState Empty => new EnvironmentState();
    }
}
