// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DbtCloud
{
    public static class GetAccountAddOns
    {
        /// <summary>
        /// Retrieve the state of every usage-based add-on product the account can use, such as dbt Wizard and dbt State.
        /// 
        /// &gt; The token needs the billing permission of the account. A product that is turned off for the account is not in the list.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DbtCloud = Pulumi.DbtCloud;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DbtCloud.GetAccountAddOns.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["addOnStates"] = .ToDictionary(item =&gt; {
        ///             var addOn = item.Value;
        ///             return addOn.Product;
        ///         }, item =&gt; {
        ///             var addOn = item.Value;
        ///             return addOn.State;
        ///         }),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Task<GetAccountAddOnsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetAccountAddOnsResult>("dbtcloud:index/getAccountAddOns:getAccountAddOns", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Retrieve the state of every usage-based add-on product the account can use, such as dbt Wizard and dbt State.
        /// 
        /// &gt; The token needs the billing permission of the account. A product that is turned off for the account is not in the list.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DbtCloud = Pulumi.DbtCloud;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DbtCloud.GetAccountAddOns.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["addOnStates"] = .ToDictionary(item =&gt; {
        ///             var addOn = item.Value;
        ///             return addOn.Product;
        ///         }, item =&gt; {
        ///             var addOn = item.Value;
        ///             return addOn.State;
        ///         }),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetAccountAddOnsResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetAccountAddOnsResult>("dbtcloud:index/getAccountAddOns:getAccountAddOns", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Retrieve the state of every usage-based add-on product the account can use, such as dbt Wizard and dbt State.
        /// 
        /// &gt; The token needs the billing permission of the account. A product that is turned off for the account is not in the list.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using DbtCloud = Pulumi.DbtCloud;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var all = DbtCloud.GetAccountAddOns.Invoke();
        /// 
        ///     return new Dictionary&lt;string, object?&gt;
        ///     {
        ///         ["addOnStates"] = .ToDictionary(item =&gt; {
        ///             var addOn = item.Value;
        ///             return addOn.Product;
        ///         }, item =&gt; {
        ///             var addOn = item.Value;
        ///             return addOn.State;
        ///         }),
        ///     };
        /// });
        /// ```
        /// </summary>
        public static Output<GetAccountAddOnsResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetAccountAddOnsResult>("dbtcloud:index/getAccountAddOns:getAccountAddOns", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetAccountAddOnsResult
    {
        /// <summary>
        /// The add-on products the account can use
        /// </summary>
        public readonly ImmutableArray<Outputs.GetAccountAddOnsAddOnResult> AddOns;

        [OutputConstructor]
        private GetAccountAddOnsResult(ImmutableArray<Outputs.GetAccountAddOnsAddOnResult> addOns)
        {
            AddOns = addOns;
        }
    }
}
