// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DbtCloud
{
    public static class GetEnvironment
    {
        /// <summary>
        /// Retrieve data for a single environment
        /// </summary>
        public static Task<GetEnvironmentResult> InvokeAsync(GetEnvironmentArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetEnvironmentResult>("dbtcloud:index/getEnvironment:getEnvironment", args ?? new GetEnvironmentArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieve data for a single environment
        /// </summary>
        public static Output<GetEnvironmentResult> Invoke(GetEnvironmentInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetEnvironmentResult>("dbtcloud:index/getEnvironment:getEnvironment", args ?? new GetEnvironmentInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Retrieve data for a single environment
        /// </summary>
        public static Output<GetEnvironmentResult> Invoke(GetEnvironmentInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetEnvironmentResult>("dbtcloud:index/getEnvironment:getEnvironment", args ?? new GetEnvironmentInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetEnvironmentArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the environment
        /// </summary>
        [Input("environmentId", required: true)]
        public int EnvironmentId { get; set; }

        /// <summary>
        /// The project ID to which the environment belongs
        /// </summary>
        [Input("projectId", required: true)]
        public int ProjectId { get; set; }

        public GetEnvironmentArgs()
        {
        }
        public static new GetEnvironmentArgs Empty => new GetEnvironmentArgs();
    }

    public sealed class GetEnvironmentInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The ID of the environment
        /// </summary>
        [Input("environmentId", required: true)]
        public Input<int> EnvironmentId { get; set; } = null!;

        /// <summary>
        /// The project ID to which the environment belongs
        /// </summary>
        [Input("projectId", required: true)]
        public Input<int> ProjectId { get; set; } = null!;

        public GetEnvironmentInvokeArgs()
        {
        }
        public static new GetEnvironmentInvokeArgs Empty => new GetEnvironmentInvokeArgs();
    }


    [OutputType]
    public sealed class GetEnvironmentResult
    {
        /// <summary>
        /// The ID of the connection to use (can be the `Id` of a `dbtcloud.GlobalConnection` or the `ConnectionId` of a legacy connection). At the moment, it is optional and the environment will use the connection set in `DbtcloudProjectConnection` if `ConnectionId` is not set in this resource. In future versions this field will become required, so it is recommended to set it from now on. When configuring this field, it needs to be configured for all the environments of the project. To avoid Terraform state issues, when using this field, the `DbtcloudProjectConnection` resource should be removed from the project or you need to make sure that the `ConnectionId` is the same in `DbtcloudProjectConnection` and in the `ConnectionId` of the Development environment of the project
        /// </summary>
        public readonly int ConnectionId;
        /// <summary>
        /// Credential ID for this environment. A credential is not required for development environments, as dbt Cloud defaults to the user's credentials, but deployment environments will have this.
        /// </summary>
        public readonly int CredentialsId;
        /// <summary>
        /// The custom branch name to use
        /// </summary>
        public readonly string CustomBranch;
        /// <summary>
        /// Version number of dbt to use in this environment.
        /// </summary>
        public readonly string DbtVersion;
        /// <summary>
        /// The type of deployment environment (currently 'production', 'staging' or empty)
        /// </summary>
        public readonly string DeploymentType;
        /// <summary>
        /// Whether model query history is on
        /// </summary>
        public readonly bool EnableModelQueryHistory;
        /// <summary>
        /// The ID of the environment
        /// </summary>
        public readonly int EnvironmentId;
        /// <summary>
        /// The ID of the extended attributes applied
        /// </summary>
        public readonly int ExtendedAttributesId;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name of the environment
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The ID of the primary profile for this environment
        /// </summary>
        public readonly int PrimaryProfileId;
        /// <summary>
        /// The project ID to which the environment belongs
        /// </summary>
        public readonly int ProjectId;
        /// <summary>
        /// The type of environment (must be either development or deployment)
        /// </summary>
        public readonly string Type;
        /// <summary>
        /// Whether to use a custom git branch in this environment
        /// </summary>
        public readonly bool UseCustomBranch;

        [OutputConstructor]
        private GetEnvironmentResult(
            int connectionId,

            int credentialsId,

            string customBranch,

            string dbtVersion,

            string deploymentType,

            bool enableModelQueryHistory,

            int environmentId,

            int extendedAttributesId,

            string id,

            string name,

            int primaryProfileId,

            int projectId,

            string type,

            bool useCustomBranch)
        {
            ConnectionId = connectionId;
            CredentialsId = credentialsId;
            CustomBranch = customBranch;
            DbtVersion = dbtVersion;
            DeploymentType = deploymentType;
            EnableModelQueryHistory = enableModelQueryHistory;
            EnvironmentId = environmentId;
            ExtendedAttributesId = extendedAttributesId;
            Id = id;
            Name = name;
            PrimaryProfileId = primaryProfileId;
            ProjectId = projectId;
            Type = type;
            UseCustomBranch = useCustomBranch;
        }
    }
}
