// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DbtCloud
{
    public static class GetPrivatelinkEndpoints
    {
        /// <summary>
        /// Privatelink endpoint data sources.
        /// </summary>
        public static Task<GetPrivatelinkEndpointsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetPrivatelinkEndpointsResult>("dbtcloud:index/getPrivatelinkEndpoints:getPrivatelinkEndpoints", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Privatelink endpoint data sources.
        /// </summary>
        public static Output<GetPrivatelinkEndpointsResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetPrivatelinkEndpointsResult>("dbtcloud:index/getPrivatelinkEndpoints:getPrivatelinkEndpoints", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Privatelink endpoint data sources.
        /// </summary>
        public static Output<GetPrivatelinkEndpointsResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetPrivatelinkEndpointsResult>("dbtcloud:index/getPrivatelinkEndpoints:getPrivatelinkEndpoints", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetPrivatelinkEndpointsResult
    {
        /// <summary>
        /// The internal ID of the PrivateLink Endpoint
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetPrivatelinkEndpointsResult(string id)
        {
            Id = id;
        }
    }
}
