// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DbtCloud
{
    /// <summary>
    /// Salesforce credential resource
    /// 
    /// ## Import
    /// 
    /// using  import blocks (requires Terraform &gt;= 1.5)
    /// import {
    /// to = dbtcloud_salesforce_credential.my_salesforce_credential
    /// id = "project_id:credential_id"
    /// }
    /// 
    /// import {
    /// to = dbtcloud_salesforce_credential.my_salesforce_credential
    /// id = "12345:6789"
    /// }
    /// 
    /// using the older import command
    /// 
    /// ```sh
    /// $ pulumi import dbtcloud:index/salesforceCredential:SalesforceCredential my_salesforce_credential "project_id:credential_id"
    /// $ pulumi import dbtcloud:index/salesforceCredential:SalesforceCredential my_salesforce_credential 12345:6789
    /// ```
    /// </summary>
    [DbtCloudResourceType("dbtcloud:index/salesforceCredential:SalesforceCredential")]
    public partial class SalesforceCredential : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The OAuth connected app client/consumer ID. Consider using `ClientIdWo` instead, which is not stored in state.
        /// </summary>
        [Output("clientId")]
        public Output<string?> ClientId { get; private set; } = null!;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Write-only alternative to `ClientId`. The value is not stored in state. Requires `ClientIdWoVersion` to trigger updates.
        /// </summary>
        [Output("clientIdWo")]
        public Output<string?> ClientIdWo { get; private set; } = null!;

        /// <summary>
        /// Version number for `ClientIdWo`. Increment this value to trigger an update of the client ID when using `ClientIdWo`.
        /// </summary>
        [Output("clientIdWoVersion")]
        public Output<int?> ClientIdWoVersion { get; private set; } = null!;

        /// <summary>
        /// The system Salesforce credential ID
        /// </summary>
        [Output("credentialId")]
        public Output<int> CredentialId { get; private set; } = null!;

        /// <summary>
        /// The number of threads to use for dbt operations
        /// </summary>
        [Output("numThreads")]
        public Output<int> NumThreads { get; private set; } = null!;

        /// <summary>
        /// The private key for JWT bearer flow authentication. Consider using `PrivateKeyWo` instead, which is not stored in state.
        /// </summary>
        [Output("privateKey")]
        public Output<string?> PrivateKey { get; private set; } = null!;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Write-only alternative to `PrivateKey`. The value is not stored in state. Requires `PrivateKeyWoVersion` to trigger updates.
        /// </summary>
        [Output("privateKeyWo")]
        public Output<string?> PrivateKeyWo { get; private set; } = null!;

        /// <summary>
        /// Version number for `PrivateKeyWo`. Increment this value to trigger an update of the private key when using `PrivateKeyWo`.
        /// </summary>
        [Output("privateKeyWoVersion")]
        public Output<int?> PrivateKeyWoVersion { get; private set; } = null!;

        /// <summary>
        /// Project ID to create the Salesforce credential in
        /// </summary>
        [Output("projectId")]
        public Output<int> ProjectId { get; private set; } = null!;

        /// <summary>
        /// Target name
        /// </summary>
        [Output("targetName")]
        public Output<string> TargetName { get; private set; } = null!;

        /// <summary>
        /// The Salesforce username for OAuth JWT bearer flow authentication
        /// </summary>
        [Output("username")]
        public Output<string> Username { get; private set; } = null!;


        /// <summary>
        /// Create a SalesforceCredential resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SalesforceCredential(string name, SalesforceCredentialArgs args, CustomResourceOptions? options = null)
            : base("dbtcloud:index/salesforceCredential:SalesforceCredential", name, args ?? new SalesforceCredentialArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SalesforceCredential(string name, Input<string> id, SalesforceCredentialState? state = null, CustomResourceOptions? options = null)
            : base("dbtcloud:index/salesforceCredential:SalesforceCredential", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumi/pulumi-dbtcloud",
                AdditionalSecretOutputs =
                {
                    "clientId",
                    "clientIdWo",
                    "privateKey",
                    "privateKeyWo",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SalesforceCredential resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SalesforceCredential Get(string name, Input<string> id, SalesforceCredentialState? state = null, CustomResourceOptions? options = null)
        {
            return new SalesforceCredential(name, id, state, options);
        }
    }

    public sealed class SalesforceCredentialArgs : global::Pulumi.ResourceArgs
    {
        [Input("clientId")]
        private Input<string>? _clientId;

        /// <summary>
        /// The OAuth connected app client/consumer ID. Consider using `ClientIdWo` instead, which is not stored in state.
        /// </summary>
        public Input<string>? ClientId
        {
            get => _clientId;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _clientId = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("clientIdWo")]
        private Input<string>? _clientIdWo;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Write-only alternative to `ClientId`. The value is not stored in state. Requires `ClientIdWoVersion` to trigger updates.
        /// </summary>
        public Input<string>? ClientIdWo
        {
            get => _clientIdWo;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _clientIdWo = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Version number for `ClientIdWo`. Increment this value to trigger an update of the client ID when using `ClientIdWo`.
        /// </summary>
        [Input("clientIdWoVersion")]
        public Input<int>? ClientIdWoVersion { get; set; }

        /// <summary>
        /// The number of threads to use for dbt operations
        /// </summary>
        [Input("numThreads")]
        public Input<int>? NumThreads { get; set; }

        [Input("privateKey")]
        private Input<string>? _privateKey;

        /// <summary>
        /// The private key for JWT bearer flow authentication. Consider using `PrivateKeyWo` instead, which is not stored in state.
        /// </summary>
        public Input<string>? PrivateKey
        {
            get => _privateKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _privateKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("privateKeyWo")]
        private Input<string>? _privateKeyWo;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Write-only alternative to `PrivateKey`. The value is not stored in state. Requires `PrivateKeyWoVersion` to trigger updates.
        /// </summary>
        public Input<string>? PrivateKeyWo
        {
            get => _privateKeyWo;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _privateKeyWo = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Version number for `PrivateKeyWo`. Increment this value to trigger an update of the private key when using `PrivateKeyWo`.
        /// </summary>
        [Input("privateKeyWoVersion")]
        public Input<int>? PrivateKeyWoVersion { get; set; }

        /// <summary>
        /// Project ID to create the Salesforce credential in
        /// </summary>
        [Input("projectId", required: true)]
        public Input<int> ProjectId { get; set; } = null!;

        /// <summary>
        /// Target name
        /// </summary>
        [Input("targetName")]
        public Input<string>? TargetName { get; set; }

        /// <summary>
        /// The Salesforce username for OAuth JWT bearer flow authentication
        /// </summary>
        [Input("username", required: true)]
        public Input<string> Username { get; set; } = null!;

        public SalesforceCredentialArgs()
        {
        }
        public static new SalesforceCredentialArgs Empty => new SalesforceCredentialArgs();
    }

    public sealed class SalesforceCredentialState : global::Pulumi.ResourceArgs
    {
        [Input("clientId")]
        private Input<string>? _clientId;

        /// <summary>
        /// The OAuth connected app client/consumer ID. Consider using `ClientIdWo` instead, which is not stored in state.
        /// </summary>
        public Input<string>? ClientId
        {
            get => _clientId;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _clientId = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("clientIdWo")]
        private Input<string>? _clientIdWo;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Write-only alternative to `ClientId`. The value is not stored in state. Requires `ClientIdWoVersion` to trigger updates.
        /// </summary>
        public Input<string>? ClientIdWo
        {
            get => _clientIdWo;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _clientIdWo = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Version number for `ClientIdWo`. Increment this value to trigger an update of the client ID when using `ClientIdWo`.
        /// </summary>
        [Input("clientIdWoVersion")]
        public Input<int>? ClientIdWoVersion { get; set; }

        /// <summary>
        /// The system Salesforce credential ID
        /// </summary>
        [Input("credentialId")]
        public Input<int>? CredentialId { get; set; }

        /// <summary>
        /// The number of threads to use for dbt operations
        /// </summary>
        [Input("numThreads")]
        public Input<int>? NumThreads { get; set; }

        [Input("privateKey")]
        private Input<string>? _privateKey;

        /// <summary>
        /// The private key for JWT bearer flow authentication. Consider using `PrivateKeyWo` instead, which is not stored in state.
        /// </summary>
        public Input<string>? PrivateKey
        {
            get => _privateKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _privateKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("privateKeyWo")]
        private Input<string>? _privateKeyWo;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Write-only alternative to `PrivateKey`. The value is not stored in state. Requires `PrivateKeyWoVersion` to trigger updates.
        /// </summary>
        public Input<string>? PrivateKeyWo
        {
            get => _privateKeyWo;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _privateKeyWo = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Version number for `PrivateKeyWo`. Increment this value to trigger an update of the private key when using `PrivateKeyWo`.
        /// </summary>
        [Input("privateKeyWoVersion")]
        public Input<int>? PrivateKeyWoVersion { get; set; }

        /// <summary>
        /// Project ID to create the Salesforce credential in
        /// </summary>
        [Input("projectId")]
        public Input<int>? ProjectId { get; set; }

        /// <summary>
        /// Target name
        /// </summary>
        [Input("targetName")]
        public Input<string>? TargetName { get; set; }

        /// <summary>
        /// The Salesforce username for OAuth JWT bearer flow authentication
        /// </summary>
        [Input("username")]
        public Input<string>? Username { get; set; }

        public SalesforceCredentialState()
        {
        }
        public static new SalesforceCredentialState Empty => new SalesforceCredentialState();
    }
}
