// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DbtCloud
{
    /// <summary>
    /// Manages the SCIM configuration for a dbt Cloud account. SCIM (System for Cross-domain Identity Management) allows identity providers such as Okta and Azure AD to automatically provision and deprovision users and groups.
    /// 
    /// This is a singleton resource — only one SCIM configuration exists per account. Destroying the resource resets the configuration to its defaults (SCIM disabled, manual updates allowed, license type not SCIM-controlled).
    /// 
    /// Requires the SCIM feature to be enabled on the account (enterprise plans only).
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using DbtCloud = Pulumi.DbtCloud;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // Enable SCIM with strict IdP control — no manual updates, license type managed by SCIM.
    ///     // This is the recommended configuration when using an identity provider such as
    ///     // Okta or Azure AD as the single source of truth for user provisioning.
    ///     var main = new DbtCloud.Index.ScimConfig("main", new()
    ///     {
    ///         Enabled = true,
    ///         ManualUpdatesAllowed = false,
    ///         ScimControlledLicenseType = true,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// Singleton resource — import using the dbt Cloud account ID.
    /// 
    /// ```sh
    /// $ pulumi import dbtcloud:index/scimConfig:ScimConfig main 12345
    /// ```
    /// </summary>
    [DbtCloudResourceType("dbtcloud:index/scimConfig:ScimConfig")]
    public partial class ScimConfig : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Whether SCIM provisioning is enabled for the account.
        /// </summary>
        [Output("enabled")]
        public Output<bool> Enabled { get; private set; } = null!;

        /// <summary>
        /// Whether administrators can manually update users and groups that are managed by SCIM. When set to ~~~false~~~, SCIM is the sole source of truth for user and group management.
        /// </summary>
        [Output("manualUpdatesAllowed")]
        public Output<bool> ManualUpdatesAllowed { get; private set; } = null!;

        /// <summary>
        /// Whether the dbt Cloud license type (Developer, Read-Only, IT) is controlled by SCIM attribute mapping. When set to ~~~false~~~, license types are managed manually inside dbt Cloud.
        /// </summary>
        [Output("scimControlledLicenseType")]
        public Output<bool> ScimControlledLicenseType { get; private set; } = null!;


        /// <summary>
        /// Create a ScimConfig resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ScimConfig(string name, ScimConfigArgs args, CustomResourceOptions? options = null)
            : base("dbtcloud:index/scimConfig:ScimConfig", name, args ?? new ScimConfigArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ScimConfig(string name, Input<string> id, ScimConfigState? state = null, CustomResourceOptions? options = null)
            : base("dbtcloud:index/scimConfig:ScimConfig", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumi/pulumi-dbtcloud",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ScimConfig resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ScimConfig Get(string name, Input<string> id, ScimConfigState? state = null, CustomResourceOptions? options = null)
        {
            return new ScimConfig(name, id, state, options);
        }
    }

    public sealed class ScimConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether SCIM provisioning is enabled for the account.
        /// </summary>
        [Input("enabled", required: true)]
        public Input<bool> Enabled { get; set; } = null!;

        /// <summary>
        /// Whether administrators can manually update users and groups that are managed by SCIM. When set to ~~~false~~~, SCIM is the sole source of truth for user and group management.
        /// </summary>
        [Input("manualUpdatesAllowed", required: true)]
        public Input<bool> ManualUpdatesAllowed { get; set; } = null!;

        /// <summary>
        /// Whether the dbt Cloud license type (Developer, Read-Only, IT) is controlled by SCIM attribute mapping. When set to ~~~false~~~, license types are managed manually inside dbt Cloud.
        /// </summary>
        [Input("scimControlledLicenseType", required: true)]
        public Input<bool> ScimControlledLicenseType { get; set; } = null!;

        public ScimConfigArgs()
        {
        }
        public static new ScimConfigArgs Empty => new ScimConfigArgs();
    }

    public sealed class ScimConfigState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether SCIM provisioning is enabled for the account.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// Whether administrators can manually update users and groups that are managed by SCIM. When set to ~~~false~~~, SCIM is the sole source of truth for user and group management.
        /// </summary>
        [Input("manualUpdatesAllowed")]
        public Input<bool>? ManualUpdatesAllowed { get; set; }

        /// <summary>
        /// Whether the dbt Cloud license type (Developer, Read-Only, IT) is controlled by SCIM attribute mapping. When set to ~~~false~~~, license types are managed manually inside dbt Cloud.
        /// </summary>
        [Input("scimControlledLicenseType")]
        public Input<bool>? ScimControlledLicenseType { get; set; }

        public ScimConfigState()
        {
        }
        public static new ScimConfigState Empty => new ScimConfigState();
    }
}
