// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DbtCloud
{
    /// <summary>
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using DbtCloud = Pulumi.DbtCloud;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     // Retrieve the SCIM-managed group
    ///     var engineering = DbtCloud.GetGroups.Invoke(new()
    ///     {
    ///         Name = "Engineering Team",
    ///     });
    /// 
    ///     // Get the project to apply permissions to
    ///     var myProject = DbtCloud.GetProject.Invoke(new()
    ///     {
    ///         Name = "My Analytics Project",
    ///     });
    /// 
    ///     // Platform team can manage base account permissions
    ///     var baseAccess = new DbtCloud.ScimGroupPartialPermissions("base_access", new()
    ///     {
    ///         GroupId = engineering.Apply(getGroupsResult =&gt; getGroupsResult.Groups[0]?.Id),
    ///         Permissions = new[]
    ///         {
    ///             new DbtCloud.Inputs.ScimGroupPartialPermissionsPermissionArgs
    ///             {
    ///                 PermissionSet = "member",
    ///                 AllProjects = true,
    ///             },
    ///         },
    ///     });
    /// 
    ///     // Project team can manage project-specific permissions independently
    ///     var projectAccess = new DbtCloud.ScimGroupPartialPermissions("project_access", new()
    ///     {
    ///         GroupId = engineering.Apply(getGroupsResult =&gt; getGroupsResult.Groups[0]?.Id),
    ///         Permissions = new[]
    ///         {
    ///             new DbtCloud.Inputs.ScimGroupPartialPermissionsPermissionArgs
    ///             {
    ///                 PermissionSet = "developer",
    ///                 ProjectId = myProject.Apply(getProjectResult =&gt; getProjectResult.Id),
    ///                 AllProjects = false,
    ///                 WritableEnvironmentCategories = new[]
    ///                 {
    ///                     "development",
    ///                     "staging",
    ///                 },
    ///             },
    ///             new DbtCloud.Inputs.ScimGroupPartialPermissionsPermissionArgs
    ///             {
    ///                 PermissionSet = "job_admin",
    ///                 ProjectId = myProject.Apply(getProjectResult =&gt; getProjectResult.Id),
    ///                 AllProjects = false,
    ///             },
    ///         },
    ///     });
    /// 
    ///     // Example: Multiple projects managed by different teams
    ///     var analytics = DbtCloud.GetProject.Invoke(new()
    ///     {
    ///         Name = "Analytics",
    ///     });
    /// 
    ///     var dataScience = DbtCloud.GetProject.Invoke(new()
    ///     {
    ///         Name = "Data Science",
    ///     });
    /// 
    ///     // Analytics team manages their own project permissions
    ///     var analyticsScimGroupPartialPermissions = new DbtCloud.ScimGroupPartialPermissions("analytics", new()
    ///     {
    ///         GroupId = engineering.Apply(getGroupsResult =&gt; getGroupsResult.Groups[0]?.Id),
    ///         Permissions = new[]
    ///         {
    ///             new DbtCloud.Inputs.ScimGroupPartialPermissionsPermissionArgs
    ///             {
    ///                 PermissionSet = "developer",
    ///                 ProjectId = analytics.Apply(getProjectResult =&gt; getProjectResult.Id),
    ///                 AllProjects = false,
    ///                 WritableEnvironmentCategories = new[]
    ///                 {
    ///                     "development",
    ///                 },
    ///             },
    ///         },
    ///     });
    /// 
    ///     // Data Science team manages their own project permissions
    ///     var dataScienceScimGroupPartialPermissions = new DbtCloud.ScimGroupPartialPermissions("data_science", new()
    ///     {
    ///         GroupId = engineering.Apply(getGroupsResult =&gt; getGroupsResult.Groups[0]?.Id),
    ///         Permissions = new[]
    ///         {
    ///             new DbtCloud.Inputs.ScimGroupPartialPermissionsPermissionArgs
    ///             {
    ///                 PermissionSet = "analyst",
    ///                 ProjectId = dataScience.Apply(getProjectResult =&gt; getProjectResult.Id),
    ///                 AllProjects = false,
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// ~&gt; **Import Not Supported:** This resource does not support `pulumi import` because it manages only a partial subset of permissions.
    /// 
    /// There is no way for Terraform to know which specific permissions this resource instance should manage versus permissions
    /// 
    /// managed by other resources or applied outside of Terraform. You must define the resource in your configuration from the start.
    /// </summary>
    [DbtCloudResourceType("dbtcloud:index/scimGroupPartialPermissions:ScimGroupPartialPermissions")]
    public partial class ScimGroupPartialPermissions : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The ID of the existing group to manage partial permissions for. This group must already exist and is typically from an external identity provider synced via SCIM.
        /// </summary>
        [Output("groupId")]
        public Output<int> GroupId { get; private set; } = null!;

        /// <summary>
        /// Partial set of permissions to apply to the group. These permissions will be added to any existing permissions. Other permissions on the group will not be affected.
        /// </summary>
        [Output("permissions")]
        public Output<ImmutableArray<Outputs.ScimGroupPartialPermissionsPermission>> Permissions { get; private set; } = null!;


        /// <summary>
        /// Create a ScimGroupPartialPermissions resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ScimGroupPartialPermissions(string name, ScimGroupPartialPermissionsArgs args, CustomResourceOptions? options = null)
            : base("dbtcloud:index/scimGroupPartialPermissions:ScimGroupPartialPermissions", name, args ?? new ScimGroupPartialPermissionsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ScimGroupPartialPermissions(string name, Input<string> id, ScimGroupPartialPermissionsState? state = null, CustomResourceOptions? options = null)
            : base("dbtcloud:index/scimGroupPartialPermissions:ScimGroupPartialPermissions", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumi/pulumi-dbtcloud",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ScimGroupPartialPermissions resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ScimGroupPartialPermissions Get(string name, Input<string> id, ScimGroupPartialPermissionsState? state = null, CustomResourceOptions? options = null)
        {
            return new ScimGroupPartialPermissions(name, id, state, options);
        }
    }

    public sealed class ScimGroupPartialPermissionsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ID of the existing group to manage partial permissions for. This group must already exist and is typically from an external identity provider synced via SCIM.
        /// </summary>
        [Input("groupId", required: true)]
        public Input<int> GroupId { get; set; } = null!;

        [Input("permissions")]
        private InputList<Inputs.ScimGroupPartialPermissionsPermissionArgs>? _permissions;

        /// <summary>
        /// Partial set of permissions to apply to the group. These permissions will be added to any existing permissions. Other permissions on the group will not be affected.
        /// </summary>
        public InputList<Inputs.ScimGroupPartialPermissionsPermissionArgs> Permissions
        {
            get => _permissions ?? (_permissions = new InputList<Inputs.ScimGroupPartialPermissionsPermissionArgs>());
            set => _permissions = value;
        }

        public ScimGroupPartialPermissionsArgs()
        {
        }
        public static new ScimGroupPartialPermissionsArgs Empty => new ScimGroupPartialPermissionsArgs();
    }

    public sealed class ScimGroupPartialPermissionsState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ID of the existing group to manage partial permissions for. This group must already exist and is typically from an external identity provider synced via SCIM.
        /// </summary>
        [Input("groupId")]
        public Input<int>? GroupId { get; set; }

        [Input("permissions")]
        private InputList<Inputs.ScimGroupPartialPermissionsPermissionGetArgs>? _permissions;

        /// <summary>
        /// Partial set of permissions to apply to the group. These permissions will be added to any existing permissions. Other permissions on the group will not be affected.
        /// </summary>
        public InputList<Inputs.ScimGroupPartialPermissionsPermissionGetArgs> Permissions
        {
            get => _permissions ?? (_permissions = new InputList<Inputs.ScimGroupPartialPermissionsPermissionGetArgs>());
            set => _permissions = value;
        }

        public ScimGroupPartialPermissionsState()
        {
        }
        public static new ScimGroupPartialPermissionsState Empty => new ScimGroupPartialPermissionsState();
    }
}
