// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DbtCloud
{
    /// <summary>
    /// Starburst/Trino credential resource
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using DbtCloud = Pulumi.DbtCloud;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new DbtCloud.StarburstCredential("example", new()
    ///     {
    ///         ProjectId = exampleDbtcloudProject.Id,
    ///         Database = "your_catalog",
    ///         Schema = "your_schema",
    ///         User = "your_user",
    ///         Password = "your_password",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// using  import blocks (requires Terraform &gt;= 1.5)
    /// 
    /// import {
    /// 
    ///   to = dbtcloud_starburst_credential.my_starburst_credential
    /// 
    ///   id = "project_id:credential_id"
    /// 
    /// }
    /// 
    /// import {
    /// 
    ///   to = dbtcloud_starburst_credential.my_starburst_credential
    /// 
    ///   id = "12345:6789"
    /// 
    /// }
    /// 
    /// using the older import command
    /// 
    /// ```sh
    /// $ pulumi import dbtcloud:index/starburstCredential:StarburstCredential my_starburst_credential "project_id:credential_id"
    /// ```
    /// 
    /// ```sh
    /// $ pulumi import dbtcloud:index/starburstCredential:StarburstCredential my_starburst_credential 12345:6789
    /// ```
    /// </summary>
    [DbtCloudResourceType("dbtcloud:index/starburstCredential:StarburstCredential")]
    public partial class StarburstCredential : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The internal credential ID
        /// </summary>
        [Output("credentialId")]
        public Output<int> CredentialId { get; private set; } = null!;

        /// <summary>
        /// The catalog to connect use
        /// </summary>
        [Output("database")]
        public Output<string> Database { get; private set; } = null!;

        /// <summary>
        /// The password for the Starburst/Trino account
        /// </summary>
        [Output("password")]
        public Output<string> Password { get; private set; } = null!;

        /// <summary>
        /// Project ID to create the Starburst/Trino credential in
        /// </summary>
        [Output("projectId")]
        public Output<int> ProjectId { get; private set; } = null!;

        /// <summary>
        /// The schema where to create models
        /// </summary>
        [Output("schema")]
        public Output<string> Schema { get; private set; } = null!;

        /// <summary>
        /// The username for the Starburst/Trino account
        /// </summary>
        [Output("user")]
        public Output<string> User { get; private set; } = null!;


        /// <summary>
        /// Create a StarburstCredential resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public StarburstCredential(string name, StarburstCredentialArgs args, CustomResourceOptions? options = null)
            : base("dbtcloud:index/starburstCredential:StarburstCredential", name, args ?? new StarburstCredentialArgs(), MakeResourceOptions(options, ""))
        {
        }

        private StarburstCredential(string name, Input<string> id, StarburstCredentialState? state = null, CustomResourceOptions? options = null)
            : base("dbtcloud:index/starburstCredential:StarburstCredential", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/pulumi/pulumi-dbtcloud",
                AdditionalSecretOutputs =
                {
                    "password",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing StarburstCredential resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static StarburstCredential Get(string name, Input<string> id, StarburstCredentialState? state = null, CustomResourceOptions? options = null)
        {
            return new StarburstCredential(name, id, state, options);
        }
    }

    public sealed class StarburstCredentialArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The catalog to connect use
        /// </summary>
        [Input("database", required: true)]
        public Input<string> Database { get; set; } = null!;

        [Input("password", required: true)]
        private Input<string>? _password;

        /// <summary>
        /// The password for the Starburst/Trino account
        /// </summary>
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Project ID to create the Starburst/Trino credential in
        /// </summary>
        [Input("projectId", required: true)]
        public Input<int> ProjectId { get; set; } = null!;

        /// <summary>
        /// The schema where to create models
        /// </summary>
        [Input("schema", required: true)]
        public Input<string> Schema { get; set; } = null!;

        /// <summary>
        /// The username for the Starburst/Trino account
        /// </summary>
        [Input("user", required: true)]
        public Input<string> User { get; set; } = null!;

        public StarburstCredentialArgs()
        {
        }
        public static new StarburstCredentialArgs Empty => new StarburstCredentialArgs();
    }

    public sealed class StarburstCredentialState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The internal credential ID
        /// </summary>
        [Input("credentialId")]
        public Input<int>? CredentialId { get; set; }

        /// <summary>
        /// The catalog to connect use
        /// </summary>
        [Input("database")]
        public Input<string>? Database { get; set; }

        [Input("password")]
        private Input<string>? _password;

        /// <summary>
        /// The password for the Starburst/Trino account
        /// </summary>
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Project ID to create the Starburst/Trino credential in
        /// </summary>
        [Input("projectId")]
        public Input<int>? ProjectId { get; set; }

        /// <summary>
        /// The schema where to create models
        /// </summary>
        [Input("schema")]
        public Input<string>? Schema { get; set; }

        /// <summary>
        /// The username for the Starburst/Trino account
        /// </summary>
        [Input("user")]
        public Input<string>? User { get; set; }

        public StarburstCredentialState()
        {
        }
        public static new StarburstCredentialState Empty => new StarburstCredentialState();
    }
}
