// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dbtcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ConnectionCatalogConfigState extends com.pulumi.resources.ResourceArgs {

    public static final ConnectionCatalogConfigState Empty = new ConnectionCatalogConfigState();

    /**
     * The ID of the global connection this catalog config is associated with. Cannot be changed after creation.
     * 
     */
    @Import(name="connectionId")
    private @Nullable Output<Integer> connectionId;

    /**
     * @return The ID of the global connection this catalog config is associated with. Cannot be changed after creation.
     * 
     */
    public Optional<Output<Integer>> connectionId() {
        return Optional.ofNullable(this.connectionId);
    }

    /**
     * List of database names to include. Supports wildcards (e.g., &#39;analytics_*&#39;). If set, only these databases are ingested.
     * 
     */
    @Import(name="databaseAllows")
    private @Nullable Output<List<String>> databaseAllows;

    /**
     * @return List of database names to include. Supports wildcards (e.g., &#39;analytics_*&#39;). If set, only these databases are ingested.
     * 
     */
    public Optional<Output<List<String>>> databaseAllows() {
        return Optional.ofNullable(this.databaseAllows);
    }

    /**
     * List of database names to exclude. Supports wildcards (e.g., &#39;staging_*&#39;). Matching databases are not ingested.
     * 
     */
    @Import(name="databaseDenies")
    private @Nullable Output<List<String>> databaseDenies;

    /**
     * @return List of database names to exclude. Supports wildcards (e.g., &#39;staging_*&#39;). Matching databases are not ingested.
     * 
     */
    public Optional<Output<List<String>>> databaseDenies() {
        return Optional.ofNullable(this.databaseDenies);
    }

    /**
     * List of schema names to include. Supports wildcards (e.g., &#39;public_*&#39;). If set, only these schemas are ingested.
     * 
     */
    @Import(name="schemaAllows")
    private @Nullable Output<List<String>> schemaAllows;

    /**
     * @return List of schema names to include. Supports wildcards (e.g., &#39;public_*&#39;). If set, only these schemas are ingested.
     * 
     */
    public Optional<Output<List<String>>> schemaAllows() {
        return Optional.ofNullable(this.schemaAllows);
    }

    /**
     * List of schema names to exclude. Supports wildcards (e.g., &#39;temp_*&#39;). Matching schemas are not ingested.
     * 
     */
    @Import(name="schemaDenies")
    private @Nullable Output<List<String>> schemaDenies;

    /**
     * @return List of schema names to exclude. Supports wildcards (e.g., &#39;temp_*&#39;). Matching schemas are not ingested.
     * 
     */
    public Optional<Output<List<String>>> schemaDenies() {
        return Optional.ofNullable(this.schemaDenies);
    }

    /**
     * List of table names to include. Supports wildcards (e.g., &#39;fact_*&#39;). If set, only these tables are ingested.
     * 
     */
    @Import(name="tableAllows")
    private @Nullable Output<List<String>> tableAllows;

    /**
     * @return List of table names to include. Supports wildcards (e.g., &#39;fact_*&#39;). If set, only these tables are ingested.
     * 
     */
    public Optional<Output<List<String>>> tableAllows() {
        return Optional.ofNullable(this.tableAllows);
    }

    /**
     * List of table names to exclude. Supports wildcards (e.g., &#39;tmp_*&#39;). Matching tables are not ingested.
     * 
     */
    @Import(name="tableDenies")
    private @Nullable Output<List<String>> tableDenies;

    /**
     * @return List of table names to exclude. Supports wildcards (e.g., &#39;tmp_*&#39;). Matching tables are not ingested.
     * 
     */
    public Optional<Output<List<String>>> tableDenies() {
        return Optional.ofNullable(this.tableDenies);
    }

    /**
     * List of view names to include. Supports wildcards (e.g., &#39;v_*&#39;). If set, only these views are ingested.
     * 
     */
    @Import(name="viewAllows")
    private @Nullable Output<List<String>> viewAllows;

    /**
     * @return List of view names to include. Supports wildcards (e.g., &#39;v_*&#39;). If set, only these views are ingested.
     * 
     */
    public Optional<Output<List<String>>> viewAllows() {
        return Optional.ofNullable(this.viewAllows);
    }

    /**
     * List of view names to exclude. Supports wildcards (e.g., &#39;secret_*&#39;). Matching views are not ingested.
     * 
     */
    @Import(name="viewDenies")
    private @Nullable Output<List<String>> viewDenies;

    /**
     * @return List of view names to exclude. Supports wildcards (e.g., &#39;secret_*&#39;). Matching views are not ingested.
     * 
     */
    public Optional<Output<List<String>>> viewDenies() {
        return Optional.ofNullable(this.viewDenies);
    }

    private ConnectionCatalogConfigState() {}

    private ConnectionCatalogConfigState(ConnectionCatalogConfigState $) {
        this.connectionId = $.connectionId;
        this.databaseAllows = $.databaseAllows;
        this.databaseDenies = $.databaseDenies;
        this.schemaAllows = $.schemaAllows;
        this.schemaDenies = $.schemaDenies;
        this.tableAllows = $.tableAllows;
        this.tableDenies = $.tableDenies;
        this.viewAllows = $.viewAllows;
        this.viewDenies = $.viewDenies;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ConnectionCatalogConfigState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ConnectionCatalogConfigState $;

        public Builder() {
            $ = new ConnectionCatalogConfigState();
        }

        public Builder(ConnectionCatalogConfigState defaults) {
            $ = new ConnectionCatalogConfigState(Objects.requireNonNull(defaults));
        }

        /**
         * @param connectionId The ID of the global connection this catalog config is associated with. Cannot be changed after creation.
         * 
         * @return builder
         * 
         */
        public Builder connectionId(@Nullable Output<Integer> connectionId) {
            $.connectionId = connectionId;
            return this;
        }

        /**
         * @param connectionId The ID of the global connection this catalog config is associated with. Cannot be changed after creation.
         * 
         * @return builder
         * 
         */
        public Builder connectionId(Integer connectionId) {
            return connectionId(Output.of(connectionId));
        }

        /**
         * @param databaseAllows List of database names to include. Supports wildcards (e.g., &#39;analytics_*&#39;). If set, only these databases are ingested.
         * 
         * @return builder
         * 
         */
        public Builder databaseAllows(@Nullable Output<List<String>> databaseAllows) {
            $.databaseAllows = databaseAllows;
            return this;
        }

        /**
         * @param databaseAllows List of database names to include. Supports wildcards (e.g., &#39;analytics_*&#39;). If set, only these databases are ingested.
         * 
         * @return builder
         * 
         */
        public Builder databaseAllows(List<String> databaseAllows) {
            return databaseAllows(Output.of(databaseAllows));
        }

        /**
         * @param databaseAllows List of database names to include. Supports wildcards (e.g., &#39;analytics_*&#39;). If set, only these databases are ingested.
         * 
         * @return builder
         * 
         */
        public Builder databaseAllows(String... databaseAllows) {
            return databaseAllows(List.of(databaseAllows));
        }

        /**
         * @param databaseDenies List of database names to exclude. Supports wildcards (e.g., &#39;staging_*&#39;). Matching databases are not ingested.
         * 
         * @return builder
         * 
         */
        public Builder databaseDenies(@Nullable Output<List<String>> databaseDenies) {
            $.databaseDenies = databaseDenies;
            return this;
        }

        /**
         * @param databaseDenies List of database names to exclude. Supports wildcards (e.g., &#39;staging_*&#39;). Matching databases are not ingested.
         * 
         * @return builder
         * 
         */
        public Builder databaseDenies(List<String> databaseDenies) {
            return databaseDenies(Output.of(databaseDenies));
        }

        /**
         * @param databaseDenies List of database names to exclude. Supports wildcards (e.g., &#39;staging_*&#39;). Matching databases are not ingested.
         * 
         * @return builder
         * 
         */
        public Builder databaseDenies(String... databaseDenies) {
            return databaseDenies(List.of(databaseDenies));
        }

        /**
         * @param schemaAllows List of schema names to include. Supports wildcards (e.g., &#39;public_*&#39;). If set, only these schemas are ingested.
         * 
         * @return builder
         * 
         */
        public Builder schemaAllows(@Nullable Output<List<String>> schemaAllows) {
            $.schemaAllows = schemaAllows;
            return this;
        }

        /**
         * @param schemaAllows List of schema names to include. Supports wildcards (e.g., &#39;public_*&#39;). If set, only these schemas are ingested.
         * 
         * @return builder
         * 
         */
        public Builder schemaAllows(List<String> schemaAllows) {
            return schemaAllows(Output.of(schemaAllows));
        }

        /**
         * @param schemaAllows List of schema names to include. Supports wildcards (e.g., &#39;public_*&#39;). If set, only these schemas are ingested.
         * 
         * @return builder
         * 
         */
        public Builder schemaAllows(String... schemaAllows) {
            return schemaAllows(List.of(schemaAllows));
        }

        /**
         * @param schemaDenies List of schema names to exclude. Supports wildcards (e.g., &#39;temp_*&#39;). Matching schemas are not ingested.
         * 
         * @return builder
         * 
         */
        public Builder schemaDenies(@Nullable Output<List<String>> schemaDenies) {
            $.schemaDenies = schemaDenies;
            return this;
        }

        /**
         * @param schemaDenies List of schema names to exclude. Supports wildcards (e.g., &#39;temp_*&#39;). Matching schemas are not ingested.
         * 
         * @return builder
         * 
         */
        public Builder schemaDenies(List<String> schemaDenies) {
            return schemaDenies(Output.of(schemaDenies));
        }

        /**
         * @param schemaDenies List of schema names to exclude. Supports wildcards (e.g., &#39;temp_*&#39;). Matching schemas are not ingested.
         * 
         * @return builder
         * 
         */
        public Builder schemaDenies(String... schemaDenies) {
            return schemaDenies(List.of(schemaDenies));
        }

        /**
         * @param tableAllows List of table names to include. Supports wildcards (e.g., &#39;fact_*&#39;). If set, only these tables are ingested.
         * 
         * @return builder
         * 
         */
        public Builder tableAllows(@Nullable Output<List<String>> tableAllows) {
            $.tableAllows = tableAllows;
            return this;
        }

        /**
         * @param tableAllows List of table names to include. Supports wildcards (e.g., &#39;fact_*&#39;). If set, only these tables are ingested.
         * 
         * @return builder
         * 
         */
        public Builder tableAllows(List<String> tableAllows) {
            return tableAllows(Output.of(tableAllows));
        }

        /**
         * @param tableAllows List of table names to include. Supports wildcards (e.g., &#39;fact_*&#39;). If set, only these tables are ingested.
         * 
         * @return builder
         * 
         */
        public Builder tableAllows(String... tableAllows) {
            return tableAllows(List.of(tableAllows));
        }

        /**
         * @param tableDenies List of table names to exclude. Supports wildcards (e.g., &#39;tmp_*&#39;). Matching tables are not ingested.
         * 
         * @return builder
         * 
         */
        public Builder tableDenies(@Nullable Output<List<String>> tableDenies) {
            $.tableDenies = tableDenies;
            return this;
        }

        /**
         * @param tableDenies List of table names to exclude. Supports wildcards (e.g., &#39;tmp_*&#39;). Matching tables are not ingested.
         * 
         * @return builder
         * 
         */
        public Builder tableDenies(List<String> tableDenies) {
            return tableDenies(Output.of(tableDenies));
        }

        /**
         * @param tableDenies List of table names to exclude. Supports wildcards (e.g., &#39;tmp_*&#39;). Matching tables are not ingested.
         * 
         * @return builder
         * 
         */
        public Builder tableDenies(String... tableDenies) {
            return tableDenies(List.of(tableDenies));
        }

        /**
         * @param viewAllows List of view names to include. Supports wildcards (e.g., &#39;v_*&#39;). If set, only these views are ingested.
         * 
         * @return builder
         * 
         */
        public Builder viewAllows(@Nullable Output<List<String>> viewAllows) {
            $.viewAllows = viewAllows;
            return this;
        }

        /**
         * @param viewAllows List of view names to include. Supports wildcards (e.g., &#39;v_*&#39;). If set, only these views are ingested.
         * 
         * @return builder
         * 
         */
        public Builder viewAllows(List<String> viewAllows) {
            return viewAllows(Output.of(viewAllows));
        }

        /**
         * @param viewAllows List of view names to include. Supports wildcards (e.g., &#39;v_*&#39;). If set, only these views are ingested.
         * 
         * @return builder
         * 
         */
        public Builder viewAllows(String... viewAllows) {
            return viewAllows(List.of(viewAllows));
        }

        /**
         * @param viewDenies List of view names to exclude. Supports wildcards (e.g., &#39;secret_*&#39;). Matching views are not ingested.
         * 
         * @return builder
         * 
         */
        public Builder viewDenies(@Nullable Output<List<String>> viewDenies) {
            $.viewDenies = viewDenies;
            return this;
        }

        /**
         * @param viewDenies List of view names to exclude. Supports wildcards (e.g., &#39;secret_*&#39;). Matching views are not ingested.
         * 
         * @return builder
         * 
         */
        public Builder viewDenies(List<String> viewDenies) {
            return viewDenies(Output.of(viewDenies));
        }

        /**
         * @param viewDenies List of view names to exclude. Supports wildcards (e.g., &#39;secret_*&#39;). Matching views are not ingested.
         * 
         * @return builder
         * 
         */
        public Builder viewDenies(String... viewDenies) {
            return viewDenies(List.of(viewDenies));
        }

        public ConnectionCatalogConfigState build() {
            return $;
        }
    }

}
