// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dbtcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetAzureDevOpsProjectArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetAzureDevOpsProjectArgs Empty = new GetAzureDevOpsProjectArgs();

    /**
     * The name of the ADO project
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return The name of the ADO project
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    private GetAzureDevOpsProjectArgs() {}

    private GetAzureDevOpsProjectArgs(GetAzureDevOpsProjectArgs $) {
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetAzureDevOpsProjectArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetAzureDevOpsProjectArgs $;

        public Builder() {
            $ = new GetAzureDevOpsProjectArgs();
        }

        public Builder(GetAzureDevOpsProjectArgs defaults) {
            $ = new GetAzureDevOpsProjectArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name The name of the ADO project
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the ADO project
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public GetAzureDevOpsProjectArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GetAzureDevOpsProjectArgs", "name");
            }
            return $;
        }
    }

}
