// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dbtcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetAzureDevOpsRepositoryArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetAzureDevOpsRepositoryArgs Empty = new GetAzureDevOpsRepositoryArgs();

    /**
     * The internal Azure Dev Ops ID of the ADO Project. Can be retrieved using the data source dbtcloud*azure*dev*ops*project and the project name
     * 
     */
    @Import(name="azureDevOpsProjectId", required=true)
    private Output<String> azureDevOpsProjectId;

    /**
     * @return The internal Azure Dev Ops ID of the ADO Project. Can be retrieved using the data source dbtcloud*azure*dev*ops*project and the project name
     * 
     */
    public Output<String> azureDevOpsProjectId() {
        return this.azureDevOpsProjectId;
    }

    /**
     * The name of the ADO repository
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return The name of the ADO repository
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    private GetAzureDevOpsRepositoryArgs() {}

    private GetAzureDevOpsRepositoryArgs(GetAzureDevOpsRepositoryArgs $) {
        this.azureDevOpsProjectId = $.azureDevOpsProjectId;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetAzureDevOpsRepositoryArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetAzureDevOpsRepositoryArgs $;

        public Builder() {
            $ = new GetAzureDevOpsRepositoryArgs();
        }

        public Builder(GetAzureDevOpsRepositoryArgs defaults) {
            $ = new GetAzureDevOpsRepositoryArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param azureDevOpsProjectId The internal Azure Dev Ops ID of the ADO Project. Can be retrieved using the data source dbtcloud*azure*dev*ops*project and the project name
         * 
         * @return builder
         * 
         */
        public Builder azureDevOpsProjectId(Output<String> azureDevOpsProjectId) {
            $.azureDevOpsProjectId = azureDevOpsProjectId;
            return this;
        }

        /**
         * @param azureDevOpsProjectId The internal Azure Dev Ops ID of the ADO Project. Can be retrieved using the data source dbtcloud*azure*dev*ops*project and the project name
         * 
         * @return builder
         * 
         */
        public Builder azureDevOpsProjectId(String azureDevOpsProjectId) {
            return azureDevOpsProjectId(Output.of(azureDevOpsProjectId));
        }

        /**
         * @param name The name of the ADO repository
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name The name of the ADO repository
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        public GetAzureDevOpsRepositoryArgs build() {
            if ($.azureDevOpsProjectId == null) {
                throw new MissingRequiredPropertyException("GetAzureDevOpsRepositoryArgs", "azureDevOpsProjectId");
            }
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GetAzureDevOpsRepositoryArgs", "name");
            }
            return $;
        }
    }

}
