// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dbtcloud.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;


public final class GetEnvironmentVariablePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetEnvironmentVariablePlainArgs Empty = new GetEnvironmentVariablePlainArgs();

    /**
     * Name for the variable, must be unique within a project, must be prefixed with &#39;DBT_&#39;
     * 
     */
    @Import(name="name", required=true)
    private String name;

    /**
     * @return Name for the variable, must be unique within a project, must be prefixed with &#39;DBT_&#39;
     * 
     */
    public String name() {
        return this.name;
    }

    /**
     * Project ID to create the environment variable in
     * 
     */
    @Import(name="projectId", required=true)
    private Integer projectId;

    /**
     * @return Project ID to create the environment variable in
     * 
     */
    public Integer projectId() {
        return this.projectId;
    }

    private GetEnvironmentVariablePlainArgs() {}

    private GetEnvironmentVariablePlainArgs(GetEnvironmentVariablePlainArgs $) {
        this.name = $.name;
        this.projectId = $.projectId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetEnvironmentVariablePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetEnvironmentVariablePlainArgs $;

        public Builder() {
            $ = new GetEnvironmentVariablePlainArgs();
        }

        public Builder(GetEnvironmentVariablePlainArgs defaults) {
            $ = new GetEnvironmentVariablePlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param name Name for the variable, must be unique within a project, must be prefixed with &#39;DBT_&#39;
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            $.name = name;
            return this;
        }

        /**
         * @param projectId Project ID to create the environment variable in
         * 
         * @return builder
         * 
         */
        public Builder projectId(Integer projectId) {
            $.projectId = projectId;
            return this;
        }

        public GetEnvironmentVariablePlainArgs build() {
            if ($.name == null) {
                throw new MissingRequiredPropertyException("GetEnvironmentVariablePlainArgs", "name");
            }
            if ($.projectId == null) {
                throw new MissingRequiredPropertyException("GetEnvironmentVariablePlainArgs", "projectId");
            }
            return $;
        }
    }

}
