// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dbtcloud.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.util.Objects;


public final class GetSnowflakeCredentialPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetSnowflakeCredentialPlainArgs Empty = new GetSnowflakeCredentialPlainArgs();

    /**
     * Credential ID
     * 
     */
    @Import(name="credentialId", required=true)
    private Integer credentialId;

    /**
     * @return Credential ID
     * 
     */
    public Integer credentialId() {
        return this.credentialId;
    }

    /**
     * Project ID
     * 
     */
    @Import(name="projectId", required=true)
    private Integer projectId;

    /**
     * @return Project ID
     * 
     */
    public Integer projectId() {
        return this.projectId;
    }

    private GetSnowflakeCredentialPlainArgs() {}

    private GetSnowflakeCredentialPlainArgs(GetSnowflakeCredentialPlainArgs $) {
        this.credentialId = $.credentialId;
        this.projectId = $.projectId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetSnowflakeCredentialPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetSnowflakeCredentialPlainArgs $;

        public Builder() {
            $ = new GetSnowflakeCredentialPlainArgs();
        }

        public Builder(GetSnowflakeCredentialPlainArgs defaults) {
            $ = new GetSnowflakeCredentialPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param credentialId Credential ID
         * 
         * @return builder
         * 
         */
        public Builder credentialId(Integer credentialId) {
            $.credentialId = credentialId;
            return this;
        }

        /**
         * @param projectId Project ID
         * 
         * @return builder
         * 
         */
        public Builder projectId(Integer projectId) {
            $.projectId = projectId;
            return this;
        }

        public GetSnowflakeCredentialPlainArgs build() {
            if ($.credentialId == null) {
                throw new MissingRequiredPropertyException("GetSnowflakeCredentialPlainArgs", "credentialId");
            }
            if ($.projectId == null) {
                throw new MissingRequiredPropertyException("GetSnowflakeCredentialPlainArgs", "projectId");
            }
            return $;
        }
    }

}
