// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dbtcloud.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetWebhookPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetWebhookPlainArgs Empty = new GetWebhookPlainArgs();

    /**
     * Webhooks ID
     * 
     */
    @Import(name="webhookId", required=true)
    private String webhookId;

    /**
     * @return Webhooks ID
     * 
     */
    public String webhookId() {
        return this.webhookId;
    }

    private GetWebhookPlainArgs() {}

    private GetWebhookPlainArgs(GetWebhookPlainArgs $) {
        this.webhookId = $.webhookId;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetWebhookPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetWebhookPlainArgs $;

        public Builder() {
            $ = new GetWebhookPlainArgs();
        }

        public Builder(GetWebhookPlainArgs defaults) {
            $ = new GetWebhookPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param webhookId Webhooks ID
         * 
         * @return builder
         * 
         */
        public Builder webhookId(String webhookId) {
            $.webhookId = webhookId;
            return this;
        }

        public GetWebhookPlainArgs build() {
            if ($.webhookId == null) {
                throw new MissingRequiredPropertyException("GetWebhookPlainArgs", "webhookId");
            }
            return $;
        }
    }

}
