// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DbtCloud.Outputs
{

    [OutputType]
    public sealed class GetPrivatelinkEndpointsEndpointResult
    {
        /// <summary>
        /// CIDR range of the PrivateLink Endpoint
        /// </summary>
        public readonly string CidrRange;
        /// <summary>
        /// The internal ID of the PrivateLink Endpoint
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Given descriptive name for the PrivateLink Endpoint
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// URL of the PrivateLink Endpoint
        /// </summary>
        public readonly string PrivateLinkEndpointUrl;
        /// <summary>
        /// Type of the PrivateLink Endpoint
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private GetPrivatelinkEndpointsEndpointResult(
            string cidrRange,

            string id,

            string name,

            string privateLinkEndpointUrl,

            string type)
        {
            CidrRange = cidrRange;
            Id = id;
            Name = name;
            PrivateLinkEndpointUrl = privateLinkEndpointUrl;
            Type = type;
        }
    }
}
