// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DbtCloud.Outputs
{

    [OutputType]
    public sealed class GlobalConnectionDatabricks
    {
        /// <summary>
        /// Catalog name if Unity Catalog is enabled in your Databricks workspace.
        /// </summary>
        public readonly string? Catalog;
        /// <summary>
        /// Required to enable Databricks OAuth authentication for IDE developers.
        /// </summary>
        public readonly string? ClientId;
        /// <summary>
        /// Required to enable Databricks OAuth authentication for IDE developers.
        /// </summary>
        public readonly string? ClientSecret;
        /// <summary>
        /// The hostname of the Databricks cluster or SQL warehouse.
        /// </summary>
        public readonly string Host;
        /// <summary>
        /// The HTTP path of the Databricks cluster or SQL warehouse.
        /// </summary>
        public readonly string HttpPath;
        /// <summary>
        /// OAuth scopes to use for the Databricks connection (e.g. `Sql`, `all-apis`). When not set, dbt Cloud relies on the default scopes (`all-apis` and `OfflineAccess`).
        /// </summary>
        public readonly ImmutableArray<string> Scopes;

        [OutputConstructor]
        private GlobalConnectionDatabricks(
            string? catalog,

            string? clientId,

            string? clientSecret,

            string host,

            string httpPath,

            ImmutableArray<string> scopes)
        {
            Catalog = catalog;
            ClientId = clientId;
            ClientSecret = clientSecret;
            Host = host;
            HttpPath = httpPath;
            Scopes = scopes;
        }
    }
}
