// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DbtCloud.Outputs
{

    [OutputType]
    public sealed class NotificationSettingChannel
    {
        /// <summary>
        /// Channel type. Currently only `Teams` is supported.
        /// </summary>
        public readonly string ChannelType;
        /// <summary>
        /// Channel ID
        /// </summary>
        public readonly int? Id;
        /// <summary>
        /// Microsoft Teams channel ID.
        /// </summary>
        public readonly string TeamsChannelId;
        /// <summary>
        /// Microsoft Teams team ID.
        /// </summary>
        public readonly string TeamsTeamId;

        [OutputConstructor]
        private NotificationSettingChannel(
            string channelType,

            int? id,

            string teamsChannelId,

            string teamsTeamId)
        {
            ChannelType = channelType;
            Id = id;
            TeamsChannelId = teamsChannelId;
            TeamsTeamId = teamsTeamId;
        }
    }
}
