// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dbtcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.dbtcloud.outputs.GetAccountAddOnsAddOn;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetAccountAddOnsResult {
    /**
     * @return The add-on products the account can use
     * 
     */
    private List<GetAccountAddOnsAddOn> addOns;

    private GetAccountAddOnsResult() {}
    /**
     * @return The add-on products the account can use
     * 
     */
    public List<GetAccountAddOnsAddOn> addOns() {
        return this.addOns;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetAccountAddOnsResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private List<GetAccountAddOnsAddOn> addOns;
        public Builder() {}
        public Builder(GetAccountAddOnsResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.addOns = defaults.addOns;
        }

        @CustomType.Setter
        public Builder addOns(List<GetAccountAddOnsAddOn> addOns) {
            if (addOns == null) {
              throw new MissingRequiredPropertyException("GetAccountAddOnsResult", "addOns");
            }
            this.addOns = addOns;
            return this;
        }
        public Builder addOns(GetAccountAddOnsAddOn... addOns) {
            return addOns(List.of(addOns));
        }
        public GetAccountAddOnsResult build() {
            final var _resultValue = new GetAccountAddOnsResult();
            _resultValue.addOns = addOns;
            return _resultValue;
        }
    }
}
