// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dbtcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetClickhouseCredentialResult {
    /**
     * @return Credential ID
     * 
     */
    private Integer credentialId;
    /**
     * @return The ID of this resource. Contains the project ID and the credential ID.
     * 
     */
    private String id;
    /**
     * @return Project ID
     * 
     */
    private Integer projectId;
    /**
     * @return The schema where to create the dbt models
     * 
     */
    private String schema;
    /**
     * @return Target name
     * 
     */
    private String targetName;
    /**
     * @return The number of threads to use for dbt operations
     * 
     */
    private Integer threads;
    /**
     * @return The ClickHouse username
     * 
     */
    private String user;

    private GetClickhouseCredentialResult() {}
    /**
     * @return Credential ID
     * 
     */
    public Integer credentialId() {
        return this.credentialId;
    }
    /**
     * @return The ID of this resource. Contains the project ID and the credential ID.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return Project ID
     * 
     */
    public Integer projectId() {
        return this.projectId;
    }
    /**
     * @return The schema where to create the dbt models
     * 
     */
    public String schema() {
        return this.schema;
    }
    /**
     * @return Target name
     * 
     */
    public String targetName() {
        return this.targetName;
    }
    /**
     * @return The number of threads to use for dbt operations
     * 
     */
    public Integer threads() {
        return this.threads;
    }
    /**
     * @return The ClickHouse username
     * 
     */
    public String user() {
        return this.user;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetClickhouseCredentialResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Integer credentialId;
        private String id;
        private Integer projectId;
        private String schema;
        private String targetName;
        private Integer threads;
        private String user;
        public Builder() {}
        public Builder(GetClickhouseCredentialResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.credentialId = defaults.credentialId;
    	      this.id = defaults.id;
    	      this.projectId = defaults.projectId;
    	      this.schema = defaults.schema;
    	      this.targetName = defaults.targetName;
    	      this.threads = defaults.threads;
    	      this.user = defaults.user;
        }

        @CustomType.Setter
        public Builder credentialId(Integer credentialId) {
            if (credentialId == null) {
              throw new MissingRequiredPropertyException("GetClickhouseCredentialResult", "credentialId");
            }
            this.credentialId = credentialId;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetClickhouseCredentialResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder projectId(Integer projectId) {
            if (projectId == null) {
              throw new MissingRequiredPropertyException("GetClickhouseCredentialResult", "projectId");
            }
            this.projectId = projectId;
            return this;
        }
        @CustomType.Setter
        public Builder schema(String schema) {
            if (schema == null) {
              throw new MissingRequiredPropertyException("GetClickhouseCredentialResult", "schema");
            }
            this.schema = schema;
            return this;
        }
        @CustomType.Setter
        public Builder targetName(String targetName) {
            if (targetName == null) {
              throw new MissingRequiredPropertyException("GetClickhouseCredentialResult", "targetName");
            }
            this.targetName = targetName;
            return this;
        }
        @CustomType.Setter
        public Builder threads(Integer threads) {
            if (threads == null) {
              throw new MissingRequiredPropertyException("GetClickhouseCredentialResult", "threads");
            }
            this.threads = threads;
            return this;
        }
        @CustomType.Setter
        public Builder user(String user) {
            if (user == null) {
              throw new MissingRequiredPropertyException("GetClickhouseCredentialResult", "user");
            }
            this.user = user;
            return this;
        }
        public GetClickhouseCredentialResult build() {
            final var _resultValue = new GetClickhouseCredentialResult();
            _resultValue.credentialId = credentialId;
            _resultValue.id = id;
            _resultValue.projectId = projectId;
            _resultValue.schema = schema;
            _resultValue.targetName = targetName;
            _resultValue.threads = threads;
            _resultValue.user = user;
            return _resultValue;
        }
    }
}
