// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dbtcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetGroupUsersUser {
    /**
     * @return Email of the user
     * 
     */
    private String email;
    /**
     * @return ID of the user
     * 
     */
    private Integer id;

    private GetGroupUsersUser() {}
    /**
     * @return Email of the user
     * 
     */
    public String email() {
        return this.email;
    }
    /**
     * @return ID of the user
     * 
     */
    public Integer id() {
        return this.id;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetGroupUsersUser defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String email;
        private Integer id;
        public Builder() {}
        public Builder(GetGroupUsersUser defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.email = defaults.email;
    	      this.id = defaults.id;
        }

        @CustomType.Setter
        public Builder email(String email) {
            if (email == null) {
              throw new MissingRequiredPropertyException("GetGroupUsersUser", "email");
            }
            this.email = email;
            return this;
        }
        @CustomType.Setter
        public Builder id(Integer id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetGroupUsersUser", "id");
            }
            this.id = id;
            return this;
        }
        public GetGroupUsersUser build() {
            final var _resultValue = new GetGroupUsersUser();
            _resultValue.email = email;
            _resultValue.id = id;
            return _resultValue;
        }
    }
}
