// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dbtcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetProfilesProfile {
    /**
     * @return The ID of the connection used by this profile
     * 
     */
    private Integer connectionId;
    /**
     * @return The ID of the credentials used by this profile
     * 
     */
    private Integer credentialsId;
    /**
     * @return The ID of the extended attributes for this profile
     * 
     */
    private Integer extendedAttributesId;
    /**
     * @return The ID of this resource. Contains the project ID and the profile ID.
     * 
     */
    private String id;
    /**
     * @return Unique identifier for the profile
     * 
     */
    private String key;
    /**
     * @return The ID of the profile
     * 
     */
    private Integer profileId;
    /**
     * @return The project ID to which the profile belongs
     * 
     */
    private Integer projectId;

    private GetProfilesProfile() {}
    /**
     * @return The ID of the connection used by this profile
     * 
     */
    public Integer connectionId() {
        return this.connectionId;
    }
    /**
     * @return The ID of the credentials used by this profile
     * 
     */
    public Integer credentialsId() {
        return this.credentialsId;
    }
    /**
     * @return The ID of the extended attributes for this profile
     * 
     */
    public Integer extendedAttributesId() {
        return this.extendedAttributesId;
    }
    /**
     * @return The ID of this resource. Contains the project ID and the profile ID.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return Unique identifier for the profile
     * 
     */
    public String key() {
        return this.key;
    }
    /**
     * @return The ID of the profile
     * 
     */
    public Integer profileId() {
        return this.profileId;
    }
    /**
     * @return The project ID to which the profile belongs
     * 
     */
    public Integer projectId() {
        return this.projectId;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetProfilesProfile defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Integer connectionId;
        private Integer credentialsId;
        private Integer extendedAttributesId;
        private String id;
        private String key;
        private Integer profileId;
        private Integer projectId;
        public Builder() {}
        public Builder(GetProfilesProfile defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.connectionId = defaults.connectionId;
    	      this.credentialsId = defaults.credentialsId;
    	      this.extendedAttributesId = defaults.extendedAttributesId;
    	      this.id = defaults.id;
    	      this.key = defaults.key;
    	      this.profileId = defaults.profileId;
    	      this.projectId = defaults.projectId;
        }

        @CustomType.Setter
        public Builder connectionId(Integer connectionId) {
            if (connectionId == null) {
              throw new MissingRequiredPropertyException("GetProfilesProfile", "connectionId");
            }
            this.connectionId = connectionId;
            return this;
        }
        @CustomType.Setter
        public Builder credentialsId(Integer credentialsId) {
            if (credentialsId == null) {
              throw new MissingRequiredPropertyException("GetProfilesProfile", "credentialsId");
            }
            this.credentialsId = credentialsId;
            return this;
        }
        @CustomType.Setter
        public Builder extendedAttributesId(Integer extendedAttributesId) {
            if (extendedAttributesId == null) {
              throw new MissingRequiredPropertyException("GetProfilesProfile", "extendedAttributesId");
            }
            this.extendedAttributesId = extendedAttributesId;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetProfilesProfile", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder key(String key) {
            if (key == null) {
              throw new MissingRequiredPropertyException("GetProfilesProfile", "key");
            }
            this.key = key;
            return this;
        }
        @CustomType.Setter
        public Builder profileId(Integer profileId) {
            if (profileId == null) {
              throw new MissingRequiredPropertyException("GetProfilesProfile", "profileId");
            }
            this.profileId = profileId;
            return this;
        }
        @CustomType.Setter
        public Builder projectId(Integer projectId) {
            if (projectId == null) {
              throw new MissingRequiredPropertyException("GetProfilesProfile", "projectId");
            }
            this.projectId = projectId;
            return this;
        }
        public GetProfilesProfile build() {
            final var _resultValue = new GetProfilesProfile();
            _resultValue.connectionId = connectionId;
            _resultValue.credentialsId = credentialsId;
            _resultValue.extendedAttributesId = extendedAttributesId;
            _resultValue.id = id;
            _resultValue.key = key;
            _resultValue.profileId = profileId;
            _resultValue.projectId = projectId;
            return _resultValue;
        }
    }
}
