// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dbtcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.dbtcloud.outputs.GetRunsFilter;
import com.pulumi.dbtcloud.outputs.GetRunsRun;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GetRunsResult {
    /**
     * @return Filter to apply to the runs
     * 
     */
    private @Nullable GetRunsFilter filter;
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    /**
     * @return Set of users with their internal ID end email
     * 
     */
    private List<GetRunsRun> runs;

    private GetRunsResult() {}
    /**
     * @return Filter to apply to the runs
     * 
     */
    public Optional<GetRunsFilter> filter() {
        return Optional.ofNullable(this.filter);
    }
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    /**
     * @return Set of users with their internal ID end email
     * 
     */
    public List<GetRunsRun> runs() {
        return this.runs;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetRunsResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable GetRunsFilter filter;
        private String id;
        private List<GetRunsRun> runs;
        public Builder() {}
        public Builder(GetRunsResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.filter = defaults.filter;
    	      this.id = defaults.id;
    	      this.runs = defaults.runs;
        }

        @CustomType.Setter
        public Builder filter(@Nullable GetRunsFilter filter) {

            this.filter = filter;
            return this;
        }
        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetRunsResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder runs(List<GetRunsRun> runs) {
            if (runs == null) {
              throw new MissingRequiredPropertyException("GetRunsResult", "runs");
            }
            this.runs = runs;
            return this;
        }
        public Builder runs(GetRunsRun... runs) {
            return runs(List.of(runs));
        }
        public GetRunsResult build() {
            final var _resultValue = new GetRunsResult();
            _resultValue.filter = filter;
            _resultValue.id = id;
            _resultValue.runs = runs;
            return _resultValue;
        }
    }
}
