// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.dbtcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class GlobalConnectionClickhouse {
    /**
     * @return The database to connect to for this connection. Default=default
     * 
     */
    private @Nullable String database;
    /**
     * @return The ClickHouse Cloud endpoint URL.
     * 
     */
    private String host;
    /**
     * @return The port to connect to for this connection. Default=8443
     * 
     */
    private @Nullable Integer port;

    private GlobalConnectionClickhouse() {}
    /**
     * @return The database to connect to for this connection. Default=default
     * 
     */
    public Optional<String> database() {
        return Optional.ofNullable(this.database);
    }
    /**
     * @return The ClickHouse Cloud endpoint URL.
     * 
     */
    public String host() {
        return this.host;
    }
    /**
     * @return The port to connect to for this connection. Default=8443
     * 
     */
    public Optional<Integer> port() {
        return Optional.ofNullable(this.port);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GlobalConnectionClickhouse defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String database;
        private String host;
        private @Nullable Integer port;
        public Builder() {}
        public Builder(GlobalConnectionClickhouse defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.database = defaults.database;
    	      this.host = defaults.host;
    	      this.port = defaults.port;
        }

        @CustomType.Setter
        public Builder database(@Nullable String database) {

            this.database = database;
            return this;
        }
        @CustomType.Setter
        public Builder host(String host) {
            if (host == null) {
              throw new MissingRequiredPropertyException("GlobalConnectionClickhouse", "host");
            }
            this.host = host;
            return this;
        }
        @CustomType.Setter
        public Builder port(@Nullable Integer port) {

            this.port = port;
            return this;
        }
        public GlobalConnectionClickhouse build() {
            final var _resultValue = new GlobalConnectionClickhouse();
            _resultValue.database = database;
            _resultValue.host = host;
            _resultValue.port = port;
            return _resultValue;
        }
    }
}
