// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DbtCloud.Inputs
{

    public sealed class GetJobJobCompletionTriggerConditionInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ID of the job that would trigger this job after completion.
        /// </summary>
        [Input("jobId", required: true)]
        public Input<int> JobId { get; set; } = null!;

        /// <summary>
        /// The ID of the project where the trigger job is running in.
        /// </summary>
        [Input("projectId", required: true)]
        public Input<int> ProjectId { get; set; } = null!;

        [Input("statuses", required: true)]
        private InputList<string>? _statuses;

        /// <summary>
        /// List of statuses to trigger the job on.
        /// </summary>
        public InputList<string> Statuses
        {
            get => _statuses ?? (_statuses = new InputList<string>());
            set => _statuses = value;
        }

        public GetJobJobCompletionTriggerConditionInputArgs()
        {
        }
        public static new GetJobJobCompletionTriggerConditionInputArgs Empty => new GetJobJobCompletionTriggerConditionInputArgs();
    }
}
