// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DbtCloud.Inputs
{

    public sealed class GlobalConnectionApacheSparkArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Auth
        /// </summary>
        [Input("auth")]
        public Input<string>? Auth { get; set; }

        /// <summary>
        /// Spark cluster for the connection
        /// </summary>
        [Input("cluster", required: true)]
        public Input<string> Cluster { get; set; } = null!;

        /// <summary>
        /// Connection retries. Default=0
        /// </summary>
        [Input("connectRetries")]
        public Input<int>? ConnectRetries { get; set; }

        /// <summary>
        /// Connection time out in seconds. Default=10
        /// </summary>
        [Input("connectTimeout")]
        public Input<int>? ConnectTimeout { get; set; }

        /// <summary>
        /// Hostname of the connection
        /// </summary>
        [Input("host", required: true)]
        public Input<string> Host { get; set; } = null!;

        /// <summary>
        /// Authentication method for the connection (http or thrift).
        /// </summary>
        [Input("method", required: true)]
        public Input<string> Method { get; set; } = null!;

        /// <summary>
        /// Organization ID
        /// </summary>
        [Input("organization")]
        public Input<string>? Organization { get; set; }

        /// <summary>
        /// Port for the connection. Default=443
        /// </summary>
        [Input("port")]
        public Input<int>? Port { get; set; }

        /// <summary>
        /// User
        /// </summary>
        [Input("user")]
        public Input<string>? User { get; set; }

        public GlobalConnectionApacheSparkArgs()
        {
        }
        public static new GlobalConnectionApacheSparkArgs Empty => new GlobalConnectionApacheSparkArgs();
    }
}
