// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.DbtCloud.Inputs
{

    public sealed class PostgresSemanticLayerCredentialCredentialGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The system Postgres/Redshift/AlloyDB credential ID.
        /// </summary>
        [Input("credentialId")]
        public Input<int>? CredentialId { get; set; }

        /// <summary>
        /// Default schema name. Optional only when semantic*layer*credential is set to true; otherwise, this field is required.
        /// </summary>
        [Input("defaultSchema")]
        public Input<string>? DefaultSchema { get; set; }

        /// <summary>
        /// The ID of this resource. Contains the project ID and the credential ID.
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// Whether the Postgres/Redshift/AlloyDB credential is active
        /// </summary>
        [Input("isActive")]
        public Input<bool>? IsActive { get; set; }

        /// <summary>
        /// Number of threads to use (required for Redshift)
        /// </summary>
        [Input("numThreads")]
        public Input<int>? NumThreads { get; set; }

        [Input("password")]
        private Input<string>? _password;

        /// <summary>
        /// Password for Postgres/Redshift/AlloyDB. Consider using `PasswordWo` instead, which is not stored in state.
        /// </summary>
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("passwordWo")]
        private Input<string>? _passwordWo;

        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// Write-only alternative to `Password`. The value is not stored in state. Requires `PasswordWoVersion` to trigger updates.
        /// </summary>
        public Input<string>? PasswordWo
        {
            get => _passwordWo;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _passwordWo = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Version number for `PasswordWo`. Increment this value to trigger an update of the password when using `PasswordWo`.
        /// </summary>
        [Input("passwordWoVersion")]
        public Input<int>? PasswordWoVersion { get; set; }

        /// <summary>
        /// Project ID to create the Postgres/Redshift/AlloyDB credential in.
        /// </summary>
        [Input("projectId", required: true)]
        public Input<int> ProjectId { get; set; } = null!;

        /// <summary>
        /// This field indicates that the credential is used as part of the Semantic Layer configuration. It is used to create a Postgres credential for the Semantic Layer.
        /// </summary>
        [Input("semanticLayerCredential")]
        public Input<bool>? SemanticLayerCredential { get; set; }

        /// <summary>
        /// Default schema name
        /// </summary>
        [Input("targetName")]
        public Input<string>? TargetName { get; set; }

        /// <summary>
        /// Type of connection. One of (postgres/redshift). Use postgres for alloydb connections. Optional only when semantic*layer*credential is set to true; otherwise, this field is required.
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        /// <summary>
        /// Username for Postgres/Redshift/AlloyDB
        /// </summary>
        [Input("username", required: true)]
        public Input<string> Username { get; set; } = null!;

        public PostgresSemanticLayerCredentialCredentialGetArgs()
        {
        }
        public static new PostgresSemanticLayerCredentialCredentialGetArgs Empty => new PostgresSemanticLayerCredentialCredentialGetArgs();
    }
}
