// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * ClickHouse credential data source
 */
export function getClickhouseCredential(args: GetClickhouseCredentialArgs, opts?: pulumi.InvokeOptions): Promise<GetClickhouseCredentialResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("dbtcloud:index/getClickhouseCredential:getClickhouseCredential", {
        "credentialId": args.credentialId,
        "projectId": args.projectId,
    }, opts);
}

/**
 * A collection of arguments for invoking getClickhouseCredential.
 */
export interface GetClickhouseCredentialArgs {
    /**
     * Credential ID
     */
    credentialId: number;
    /**
     * Project ID
     */
    projectId: number;
}

/**
 * A collection of values returned by getClickhouseCredential.
 */
export interface GetClickhouseCredentialResult {
    /**
     * Credential ID
     */
    readonly credentialId: number;
    /**
     * The ID of this resource. Contains the project ID and the credential ID.
     */
    readonly id: string;
    /**
     * Project ID
     */
    readonly projectId: number;
    /**
     * The schema where to create the dbt models
     */
    readonly schema: string;
    /**
     * Target name
     */
    readonly targetName: string;
    /**
     * The number of threads to use for dbt operations
     */
    readonly threads: number;
    /**
     * The ClickHouse username
     */
    readonly user: string;
}
/**
 * ClickHouse credential data source
 */
export function getClickhouseCredentialOutput(args: GetClickhouseCredentialOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetClickhouseCredentialResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("dbtcloud:index/getClickhouseCredential:getClickhouseCredential", {
        "credentialId": args.credentialId,
        "projectId": args.projectId,
    }, opts);
}

/**
 * A collection of arguments for invoking getClickhouseCredential.
 */
export interface GetClickhouseCredentialOutputArgs {
    /**
     * Credential ID
     */
    credentialId: pulumi.Input<number>;
    /**
     * Project ID
     */
    projectId: pulumi.Input<number>;
}
